#[cfg(target_os = "windows")]
pub mod amd;
pub mod asus;
pub mod corsair;
pub mod generic;
pub mod logitech;
pub mod nvidia;
pub mod nzxt;
pub mod philips;
pub mod razer;
pub mod steelseries;
pub mod zotac;
