// SPDX-License-Identifier: GPL-3.0-or-later
//! Settings page — matches the GTK GUI's settings content while using the
//! Prism design visual layout (cards with toggles, value chips, buttons).

use crate::ui::components as widgets;
use egui::{Align, Align2, Color32, Pos2, Rect, Sense, Stroke, Vec2};
use halod_shared::commands::EngineKind;
use halod_shared::debug_info::{DebugInfo, DependencyStatus};
use halod_shared::types::{AppState, DiscoveryPhase};

use crate::runtime::ipc::CommandTx;
use crate::ui::screens::depcheck::{fix_text, impact_text, title_text};
use crate::ui::theme;

/// Embedded third-party license text (generated by build.rs).
const THIRD_PARTY_LICENSES: &str =
    include_str!(concat!(env!("OUT_DIR"), "/third_party_licenses.txt"));

// ── State ─────────────────────────────────────────────────────────────────────

#[derive(Default)]
pub struct SettingsUi {
    /// Which modal overlay is currently open.
    modal: Option<Modal>,
    /// Set once we've asked the daemon for `DebugInfo` to populate the
    /// dependency panel, so we don't re-request it every frame.
    deps_requested: bool,
    /// Cached OS "launch at login" state; seeded on first render so the
    /// toggle doesn't hit the filesystem/registry every frame. `None` until
    /// seeded.
    start_on_boot: Option<bool>,
}

enum Modal {
    Licenses,
    Credits,
    Diagnostics,
}

// ── Entry point ───────────────────────────────────────────────────────────────

pub fn show(
    ui: &mut egui::Ui,
    state: &AppState,
    cmd: &CommandTx,
    connected: bool,
    debug: Option<&DebugInfo>,
    st: &mut SettingsUi,
) {
    if !connected {
        st.deps_requested = false;
    }
    // Lazily pull a DebugInfo snapshot the first time Settings is shown while
    // connected; it feeds both the dependency panel and the diagnostics modal.
    if connected && !st.deps_requested {
        crate::domain::actions::system::get_debug_info(cmd);
        st.deps_requested = true;
    }

    egui::ScrollArea::vertical()
        .auto_shrink([false, false])
        .show(ui, |ui| {
            widgets::page_frame(ui, |ui| {
                page_body(ui, state, cmd, connected, debug, st);
            });
        });

    // ── Modals (drawn on top, not inside the scroll) ──────────────────────
    match st.modal {
        Some(Modal::Licenses) => {
            licenses_modal(ui.ctx(), st);
        }
        Some(Modal::Credits) => {
            credits_modal(ui.ctx(), st);
        }
        Some(Modal::Diagnostics) => {
            diagnostics_modal(ui.ctx(), debug, st);
        }
        None => {}
    }
}

// ── Page body ─────────────────────────────────────────────────────────────────

#[allow(clippy::too_many_arguments)]
fn page_body(
    ui: &mut egui::Ui,
    state: &AppState,
    cmd: &CommandTx,
    connected: bool,
    debug: Option<&DebugInfo>,
    st: &mut SettingsUi,
) {
    ui.label(
        egui::RichText::new(t!("settings.title"))
            .font(theme::bold(22.0))
            .color(theme::TEXT),
    );
    ui.add_space(3.0);
    ui.label(
        egui::RichText::new(t!("settings.subtitle"))
            .font(theme::body(12.0))
            .color(theme::TEXT_MUT),
    );
    ui.add_space(22.0);

    // ── APPLICATION ───────────────────────────────────────────────────────
    section_header(ui, &t!("settings.section_application"));
    ui.add_space(4.0);
    let app_card = ui.scope(|ui| {
        widgets::card(ui, |ui| {
            ui.spacing_mut().item_spacing.y = 0.0;
            start_on_boot_row(ui, st);
            language_row(ui, state, cmd);
            close_to_tray_row(ui, state, cmd);
            window_controls_row(ui, state, cmd);
            dependency_warning_row(ui, state, cmd);
            plugin_downloads_row(ui, state, cmd);
            replay_tutorials_row(ui, cmd);
        });
    });
    crate::domain::tour::anchor(
        ui.ctx(),
        crate::domain::tour::AnchorId::SettingsApplication,
        app_card.response.rect,
    );
    ui.add_space(18.0);

    // ── ENGINES ───────────────────────────────────────────────────────────
    section_header(ui, &t!("settings.section_engines"));
    ui.add_space(4.0);
    let engines_card = ui.scope(|ui| {
        widgets::card(ui, |ui| {
            ui.spacing_mut().item_spacing.y = 0.0;
            lcd_engine_row(ui, state, cmd);
        });
    });
    crate::domain::tour::anchor(
        ui.ctx(),
        crate::domain::tour::AnchorId::SettingsEngines,
        engines_card.response.rect,
    );
    ui.add_space(18.0);

    // ── DEVICES ───────────────────────────────────────────────────────────
    section_header(ui, &t!("settings.section_devices"));
    ui.add_space(4.0);
    widgets::card(ui, |ui| {
        ui.spacing_mut().item_spacing.y = 0.0;
        daemon_status_row(ui, connected);
        rediscover_row(ui, state, cmd);
    });
    ui.add_space(18.0);

    // ── HEALTHCHECK ───────────────────────────────────────────────────────
    healthcheck_section(ui, cmd, debug);
    ui.add_space(18.0);

    // ── LOGGING ───────────────────────────────────────────────────────────
    section_header(ui, &t!("settings.section_logging"));
    ui.add_space(4.0);
    widgets::card(ui, |ui| {
        ui.spacing_mut().item_spacing.y = 0.0;
        log_level_row(ui, state, cmd);
        log_viewer_row(ui, state);
    });
    ui.add_space(18.0);

    // ── ADVANCED ──────────────────────────────────────────────────────────
    section_header(ui, &t!("settings.section_advanced"));
    ui.add_space(4.0);
    widgets::card(ui, |ui| {
        ui.spacing_mut().item_spacing.y = 0.0;
        config_folder_row(ui, state);
    });
    ui.add_space(18.0);

    // ── DEBUG ─────────────────────────────────────────────────────────────
    section_header(ui, &t!("settings.section_debug"));
    ui.add_space(4.0);
    widgets::card(ui, |ui| {
        ui.spacing_mut().item_spacing.y = 0.0;
        diagnostics_row(ui, cmd, st);
    });
    ui.add_space(18.0);

    // ── ABOUT ─────────────────────────────────────────────────────────────
    section_header(ui, &t!("settings.section_about"));
    ui.add_space(4.0);
    widgets::card(ui, |ui| {
        ui.spacing_mut().item_spacing.y = 0.0;
        about_row(ui, st);
        third_party_row(ui, st);
        repo_row(ui);
    });

    ui.add_space(24.0);
    footer(ui, state);
}

// ── Shared helpers ────────────────────────────────────────────────────────────

fn row_rect(ui: &mut egui::Ui) -> Rect {
    let (rect, _) = ui.allocate_exact_size(Vec2::new(ui.available_width(), 52.0), Sense::hover());
    rect
}

fn row_label(ui: &mut egui::Ui, rect: Rect, title: &str, subtitle: &str) {
    ui.painter().text(
        Pos2::new(rect.left(), rect.top() + 10.0),
        Align2::LEFT_TOP,
        title,
        theme::body(12.5),
        theme::TEXT,
    );
    ui.painter().text(
        Pos2::new(rect.left(), rect.top() + 28.0),
        Align2::LEFT_TOP,
        subtitle,
        theme::body(10.5),
        theme::TEXT_FAINT,
    );
}

fn bottom_border(ui: &mut egui::Ui, rect: Rect) {
    ui.painter().line_segment(
        [rect.left_bottom(), rect.right_bottom()],
        Stroke::new(1.0, theme::BORDER_SOFT),
    );
}

fn row_toggle(ui: &mut egui::Ui, rect: Rect, on: bool, id: &str) -> bool {
    row_toggle_at(ui, rect.right() - 36.0, rect.top() + 17.0, on, id)
}

fn row_toggle_at(ui: &mut egui::Ui, x: f32, y: f32, on: bool, id: &str) -> bool {
    let toggle_rect = Rect::from_min_size(Pos2::new(x, y), Vec2::new(28.0, 15.0));
    let resp = ui.interact(toggle_rect, ui.id().with(("toggle", id)), Sense::click());
    let t = ui.ctx().animate_bool_with_time(resp.id, on, 0.15);
    widgets::paint_toggle(ui.painter(), toggle_rect, t);
    if resp.hovered() {
        ui.ctx().set_cursor_icon(egui::CursorIcon::PointingHand);
    }
    resp.clicked()
}

fn right_button(ui: &mut egui::Ui, rect: Rect, label: &str, st: &mut SettingsUi, modal: Modal) {
    let btn_w = 80.0_f32.max(
        ui.painter()
            .layout_no_wrap(label.to_string(), theme::body(11.5), theme::TEXT)
            .size()
            .x
            + 20.0,
    );
    let btn_rect = Rect::from_min_size(
        Pos2::new(rect.right() - btn_w, rect.top() + 10.0),
        Vec2::new(btn_w, 30.0),
    );
    let mut btn_ui = ui.new_child(egui::UiBuilder::new().max_rect(btn_rect).layout(
        egui::Layout::centered_and_justified(egui::Direction::LeftToRight),
    ));
    if widgets::button(
        &mut btn_ui,
        label,
        widgets::ButtonKind::Ghost,
        Vec2::new(btn_w, 30.0),
    )
    .clicked()
    {
        st.modal = Some(modal);
    }
}

// ── APPLICATION rows ──────────────────────────────────────────────────────────

/// New cached toggle state after an autostart write: adopt `new` on success,
/// keep `prev` on failure.
fn cache_after_toggle(prev: Option<bool>, new: bool, ok: bool) -> Option<bool> {
    if ok {
        Some(new)
    } else {
        prev
    }
}

fn start_on_boot_row(ui: &mut egui::Ui, st: &mut SettingsUi) {
    let rect = row_rect(ui);
    if crate::domain::lifecycle::autostart::system_managed() {
        row_label(
            ui,
            rect,
            &t!("settings.start_on_boot_title"),
            &t!("settings.start_on_boot_managed_sub"),
        );
        ui.painter().text(
            Pos2::new(rect.right(), rect.center().y),
            Align2::RIGHT_CENTER,
            t!("settings.start_on_boot_managed_value"),
            theme::body(10.5),
            theme::TEXT_FAINT,
        );
        bottom_border(ui, rect);
        return;
    }
    row_label(
        ui,
        rect,
        &t!("settings.start_on_boot_title"),
        &t!("settings.start_on_boot_sub"),
    );
    let on = *st
        .start_on_boot
        .get_or_insert_with(crate::domain::lifecycle::autostart::is_enabled);
    if row_toggle(ui, rect, on, "start_on_boot") {
        let ok = crate::domain::lifecycle::autostart::set_enabled(!on)
            .map_err(|e| log::error!("autostart toggle failed: {e}"))
            .is_ok();
        st.start_on_boot = cache_after_toggle(st.start_on_boot, !on, ok);
    }
    bottom_border(ui, rect);
}

fn close_to_tray_row(ui: &mut egui::Ui, state: &AppState, cmd: &CommandTx) {
    let rect = row_rect(ui);
    row_label(
        ui,
        rect,
        &t!("settings.close_to_tray_title"),
        &t!("settings.close_to_tray_sub"),
    );
    let on = state.gui.close_to_tray;
    if row_toggle(ui, rect, on, "close_to_tray") {
        crate::domain::actions::system::set_ui_config(
            cmd,
            !on,
            state.gui.suppress_dependency_warning,
            state.gui.hide_window_controls,
        );
    }
    bottom_border(ui, rect);
}

fn plugin_downloads_row(ui: &mut egui::Ui, state: &AppState, cmd: &CommandTx) {
    let rect = row_rect(ui);
    row_label(
        ui,
        rect,
        &t!("settings.plugin_downloads_title"),
        &t!("settings.plugin_downloads_sub"),
    );
    let on = state.gui.plugin_downloads == halod_shared::types::PluginDownloadConsent::Allowed;
    if row_toggle(ui, rect, on, "plugin_downloads") {
        crate::domain::actions::system::set_plugin_download_consent(cmd, !on);
    }
    bottom_border(ui, rect);
}

fn window_controls_row(ui: &mut egui::Ui, state: &AppState, cmd: &CommandTx) {
    let rect = row_rect(ui);
    row_label(
        ui,
        rect,
        &t!("settings.window_controls_title"),
        &t!("settings.window_controls_sub"),
    );
    let on = !state.gui.hide_window_controls;
    if row_toggle(ui, rect, on, "window_controls") {
        crate::domain::actions::system::set_ui_config(
            cmd,
            state.gui.close_to_tray,
            state.gui.suppress_dependency_warning,
            on,
        );
    }
    bottom_border(ui, rect);
}

fn dependency_warning_row(ui: &mut egui::Ui, state: &AppState, cmd: &CommandTx) {
    let rect = row_rect(ui);
    row_label(
        ui,
        rect,
        &t!("settings.startup_healthcheck_title"),
        &t!("settings.startup_healthcheck_sub"),
    );
    let warn_on = !state.gui.suppress_dependency_warning;
    if row_toggle(ui, rect, warn_on, "dependency_warning") {
        crate::domain::actions::system::set_ui_config(
            cmd,
            state.gui.close_to_tray,
            warn_on,
            state.gui.hide_window_controls,
        );
    }
    bottom_border(ui, rect);
}

fn replay_tutorials_row(ui: &mut egui::Ui, cmd: &CommandTx) {
    let rect = row_rect(ui);
    row_label(
        ui,
        rect,
        &t!("settings.replay_tutorials_title"),
        &t!("settings.replay_tutorials_sub"),
    );

    let btn_w = 90.0;
    let btn_rect = Rect::from_min_size(
        Pos2::new(rect.right() - btn_w, rect.top() + 10.0),
        Vec2::new(btn_w, 30.0),
    );
    let mut btn_ui = ui.new_child(egui::UiBuilder::new().max_rect(btn_rect).layout(
        egui::Layout::centered_and_justified(egui::Direction::LeftToRight),
    ));
    if widgets::button(
        &mut btn_ui,
        &t!("settings.replay_button"),
        widgets::ButtonKind::Ghost,
        Vec2::new(btn_w, 30.0),
    )
    .clicked()
    {
        crate::domain::actions::system::reset_tours_seen(cmd);
        crate::domain::tour::request_reset(ui.ctx());
    }
    bottom_border(ui, rect);
}

// ── ENGINES rows ──────────────────────────────────────────────────────────────

fn lcd_engine_row(ui: &mut egui::Ui, state: &AppState, cmd: &CommandTx) {
    let rect = row_rect(ui);
    row_label(ui, rect, "LCD", &t!("settings.lcd_engine_sub"));

    let lcd_enabled = state.lcd.config.enabled;
    let lcd_fps = state.lcd.config.fps;

    let chip_w = 72.0_f32;
    let fps_chip_rect = Rect::from_min_size(
        Pos2::new(rect.right() - chip_w - 40.0, rect.top() + 10.0),
        Vec2::new(chip_w, 30.0),
    );

    // Numeric-only fps input; re-seeded from config while unfocused, committed
    // on Enter or when focus leaves (clamped to the valid 1..=60 range).
    let fps_id = ui.id().with("lcd_fps");
    let mut buf = ui
        .data(|d| d.get_temp::<String>(fps_id))
        .unwrap_or_default();
    if !ui.memory(|m| m.has_focus(fps_id)) {
        buf = lcd_fps.to_string();
    }
    let mut chip_ui = ui.new_child(egui::UiBuilder::new().max_rect(fps_chip_rect).layout(
        egui::Layout::centered_and_justified(egui::Direction::LeftToRight),
    ));
    let resp = chip_ui.add_enabled(
        lcd_enabled,
        egui::TextEdit::singleline(&mut buf)
            .id(fps_id)
            .font(theme::mono_semibold(11.0))
            .horizontal_align(Align::Center)
            .desired_width(chip_w)
            .margin(egui::vec2(8.0, 6.0)),
    );
    buf.retain(|c| c.is_ascii_digit());
    if resp.lost_focus() {
        let clamped = parse_fps(&buf, lcd_fps);
        buf = clamped.to_string();
        if clamped != lcd_fps {
            crate::domain::actions::system::set_engine_fps(cmd, EngineKind::Lcd, clamped as u64);
        }
    }
    ui.data_mut(|d| d.insert_temp(fps_id, buf));

    let toggle_x = rect.right() - 36.0;
    let toggle_y = rect.top() + 17.0;
    if row_toggle_at(ui, toggle_x, toggle_y, lcd_enabled, "lcd") {
        crate::domain::actions::system::set_engine_enabled(cmd, EngineKind::Lcd, !lcd_enabled);
    }

    bottom_border(ui, rect);
}

// ── DEVICES rows ──────────────────────────────────────────────────────────────

fn daemon_status_row(ui: &mut egui::Ui, connected: bool) {
    let rect = row_rect(ui);
    let (status_text, status_color) = if connected {
        (t!("settings.daemon_connected"), theme::TRAFFIC_GREEN)
    } else {
        (t!("settings.daemon_disconnected"), theme::OFFLINE)
    };
    row_label(
        ui,
        rect,
        &t!("settings.daemon_title"),
        &t!("settings.daemon_sub"),
    );
    ui.painter().text(
        Pos2::new(rect.right() - 10.0, rect.top() + 12.0),
        Align2::RIGHT_TOP,
        status_text,
        theme::mono_semibold(11.0),
        status_color,
    );
    bottom_border(ui, rect);
}

fn is_scanning(state: &AppState) -> bool {
    matches!(state.discovery.phase, DiscoveryPhase::Discovering)
}

fn rediscover_row(ui: &mut egui::Ui, state: &AppState, cmd: &CommandTx) {
    let rect = row_rect(ui);
    row_label(
        ui,
        rect,
        &t!("settings.rediscover_title"),
        &t!("settings.rediscover_sub"),
    );

    let btn_w = 90.0;
    let btn_rect = Rect::from_min_size(
        Pos2::new(rect.right() - btn_w, rect.top() + 10.0),
        Vec2::new(btn_w, 30.0),
    );
    let mut btn_ui = ui.new_child(egui::UiBuilder::new().max_rect(btn_rect).layout(
        egui::Layout::centered_and_justified(egui::Direction::LeftToRight),
    ));
    let btn_size = Vec2::new(btn_w, 30.0);
    if is_scanning(state) {
        widgets::button_loading(
            &mut btn_ui,
            &t!("settings.scanning_button"),
            widgets::ButtonKind::Ghost,
            btn_size,
        );
    } else if widgets::button(
        &mut btn_ui,
        &t!("settings.scan_now_button"),
        widgets::ButtonKind::Ghost,
        btn_size,
    )
    .clicked()
    {
        crate::domain::actions::system::rediscover(cmd);
    }

    bottom_border(ui, rect);
}

// ── HEALTHCHECK rows ───────────────────────────────────────────────────────────

fn healthcheck_section(ui: &mut egui::Ui, cmd: &CommandTx, debug: Option<&DebugInfo>) {
    let (rect, _) = ui.allocate_exact_size(Vec2::new(ui.available_width(), 20.0), Sense::hover());
    ui.painter().text(
        Pos2::new(rect.left(), rect.center().y),
        Align2::LEFT_CENTER,
        t!("settings.section_healthcheck"),
        theme::body(10.0),
        theme::TEXT_FAINT2,
    );
    let btn_w = 76.0;
    let btn_rect = Rect::from_min_size(
        Pos2::new(rect.right() - btn_w, rect.top() - 4.0),
        Vec2::new(btn_w, 26.0),
    );
    let mut btn_ui = ui.new_child(egui::UiBuilder::new().max_rect(btn_rect).layout(
        egui::Layout::centered_and_justified(egui::Direction::LeftToRight),
    ));
    if widgets::button(
        &mut btn_ui,
        &t!("settings.recheck_button"),
        widgets::ButtonKind::Ghost,
        Vec2::new(btn_w, 26.0),
    )
    .clicked()
    {
        crate::domain::actions::system::get_debug_info(cmd);
    }
    ui.add_space(4.0);

    widgets::card(ui, |ui| {
        ui.spacing_mut().item_spacing.y = 0.0;
        match debug {
            None => {
                let rect = row_rect(ui);
                row_label(
                    ui,
                    rect,
                    &t!("settings.running_healthcheck_title"),
                    &t!("settings.running_healthcheck_sub"),
                );
                bottom_border(ui, rect);
            }
            Some(info) if info.dependencies.is_empty() => {
                let rect = row_rect(ui);
                row_label(
                    ui,
                    rect,
                    &t!("settings.no_checks_title"),
                    &t!("settings.no_checks_sub"),
                );
                bottom_border(ui, rect);
            }
            Some(info) => {
                for dep in &info.dependencies {
                    dependency_row(ui, dep);
                }
            }
        }
    });
}

fn dependency_row(ui: &mut egui::Ui, dep: &DependencyStatus) {
    let rect = row_rect(ui);

    let name = title_text(dep);
    let title = if dep.platform.is_empty() || dep.platform == "All" {
        name
    } else {
        format!("{}  ·  {}", name, dep.platform)
    };
    // Show the actionable fix in place of the purpose when it's missing.
    let subtitle = if !dep.present {
        fix_text(dep)
    } else {
        impact_text(dep)
    };
    row_label(ui, rect, &title, &subtitle);

    // Status (line 1): green when detected; red only when a *required* dep is
    // absent; otherwise a neutral grey — a missing optional tool is just info.
    let (status, status_color) = if dep.present {
        (t!("settings.dep_detected"), theme::TRAFFIC_GREEN)
    } else if dep.required {
        (t!("settings.dep_missing"), theme::OFFLINE)
    } else {
        (t!("settings.dep_not_found"), theme::TEXT_FAINT)
    };
    ui.painter().text(
        Pos2::new(rect.right() - 10.0, rect.top() + 9.0),
        Align2::RIGHT_TOP,
        status,
        theme::mono_semibold(11.0),
        status_color,
    );

    // Tag (line 2): "Required" (red only when unmet) or a muted "Optional".
    let (tag, tag_color) = if dep.required {
        (
            t!("settings.dep_required"),
            if dep.present {
                theme::TEXT_MUT
            } else {
                theme::OFFLINE
            },
        )
    } else {
        (t!("settings.dep_optional"), theme::TEXT_MUT)
    };
    tag_pill(ui, rect.right() - 10.0, rect.top() + 30.0, &tag, tag_color);

    bottom_border(ui, rect);
}

/// A small right-anchored pill (rounded outline + label).
fn tag_pill(ui: &mut egui::Ui, right: f32, y: f32, text: &str, color: Color32) {
    let font = theme::body(9.5);
    let text_w = ui
        .painter()
        .layout_no_wrap(text.to_string(), font.clone(), color)
        .size()
        .x;
    let w = text_w + 14.0;
    let h = 16.0;
    let pill = Rect::from_min_size(Pos2::new(right - w, y), Vec2::new(w, h));
    ui.painter().rect_filled(pill, 8.0, theme::hex(0x14131f));
    ui.painter()
        .rect_stroke(pill, 8.0, Stroke::new(1.0, color), egui::StrokeKind::Middle);
    ui.painter()
        .text(pill.center(), Align2::CENTER_CENTER, text, font, color);
}

// ── Language ────────────────────────────────────────────────────────────────

/// Supported UI languages as `(code, native display name)`. Codes must match
/// `halod_shared::types::SUPPORTED_LANGUAGES`; the parity is asserted in tests.
const LANGUAGES: &[(&str, &str)] = &[("en", "English"), ("it", "Italiano")];

/// Native display name for a language code, falling back to the code itself.
fn language_display(code: &str) -> &str {
    LANGUAGES
        .iter()
        .find(|(c, _)| *c == code)
        .map(|(_, name)| *name)
        .unwrap_or(code)
}

/// Apply `code` as the active translation locale, unless it is already active.
pub fn apply_locale(code: &str) {
    if &*rust_i18n::locale() != code {
        rust_i18n::set_locale(code);
    }
}

fn language_row(ui: &mut egui::Ui, state: &AppState, cmd: &CommandTx) {
    let rect = row_rect(ui);
    row_label(ui, rect, &t!("settings.language"), "");

    let current = state.gui.language.as_str();
    let combo_w = 130.0;
    let combo_rect = Rect::from_min_size(
        Pos2::new(rect.right() - combo_w, rect.top() + 11.0),
        Vec2::new(combo_w, 30.0),
    );
    let mut combo_ui = ui.new_child(
        egui::UiBuilder::new()
            .max_rect(combo_rect)
            .layout(egui::Layout::top_down(egui::Align::Min)),
    );
    let mut picked: Option<&str> = None;
    egui::ComboBox::from_id_salt("language_select")
        .selected_text(language_display(current))
        .width(combo_w)
        .show_ui(&mut combo_ui, |ui| {
            for (code, name) in LANGUAGES {
                if ui.selectable_label(current == *code, *name).clicked() {
                    picked = Some(code);
                }
            }
        });
    if let Some(code) = picked {
        if code != current {
            crate::domain::actions::system::set_language(cmd, code);
        }
    }

    bottom_border(ui, rect);
}

// ── LOGGING rows ──────────────────────────────────────────────────────────────

const LOG_LEVELS: &[&str] = &["error", "warn", "info", "debug", "trace"];

fn log_level_row(ui: &mut egui::Ui, state: &AppState, cmd: &CommandTx) {
    let rect = row_rect(ui);
    row_label(
        ui,
        rect,
        &t!("settings.log_level"),
        &t!("settings.log_level_sub"),
    );

    let current = state.gui.log_level.to_lowercase();
    let combo_w = 130.0;
    let combo_rect = Rect::from_min_size(
        Pos2::new(rect.right() - combo_w, rect.top() + 11.0),
        Vec2::new(combo_w, 30.0),
    );
    let mut combo_ui = ui.new_child(
        egui::UiBuilder::new()
            .max_rect(combo_rect)
            .layout(egui::Layout::top_down(egui::Align::Min)),
    );
    let mut picked: Option<&str> = None;
    egui::ComboBox::from_id_salt("log_level_select")
        .selected_text(current.clone())
        .width(combo_w)
        .show_ui(&mut combo_ui, |ui| {
            for &level in LOG_LEVELS {
                if ui.selectable_label(current == level, level).clicked() {
                    picked = Some(level);
                }
            }
        });
    if let Some(level) = picked {
        if level != current {
            crate::domain::actions::system::set_log_level(cmd, level);
        }
    }

    bottom_border(ui, rect);
}

fn log_viewer_row(ui: &mut egui::Ui, state: &AppState) {
    let header_h = 40.0;
    let viewer_h = 240.0;
    let total_h = header_h + viewer_h;

    let (rect, _) =
        ui.allocate_exact_size(Vec2::new(ui.available_width(), total_h), Sense::hover());

    ui.painter().text(
        Pos2::new(rect.left(), rect.top() + 6.0),
        Align2::LEFT_TOP,
        t!("settings.live_log_title"),
        theme::body(12.5),
        theme::TEXT,
    );
    ui.painter().text(
        Pos2::new(rect.left(), rect.top() + 24.0),
        Align2::LEFT_TOP,
        t!("settings.log_entries", n = state.log_entries.len()),
        theme::body(10.5),
        theme::TEXT_FAINT,
    );

    let log_rect = Rect::from_min_size(
        Pos2::new(rect.left(), rect.top() + header_h),
        Vec2::new(rect.width(), viewer_h),
    );
    ui.painter()
        .rect_filled(log_rect, 8.0, theme::hex(0x080b10));
    ui.painter().rect_stroke(
        log_rect,
        8.0,
        Stroke::new(1.0, theme::hex(0x1c2230)),
        egui::StrokeKind::Middle,
    );

    let mut log_ui = ui.new_child(egui::UiBuilder::new().max_rect(log_rect.shrink(8.0)));
    log_ui.shrink_clip_rect(log_rect);
    log_ui.spacing_mut().item_spacing.y = 1.0;
    egui::ScrollArea::both()
        .auto_shrink([false, false])
        .stick_to_bottom(true)
        .show(&mut log_ui, |ui| {
            for entry in &state.log_entries {
                let level_color = match entry.level.to_lowercase().as_str() {
                    "error" | "err" => theme::OFFLINE,
                    "warn" | "warning" => theme::STAT_AMBER,
                    "info" => theme::CYAN,
                    _ => theme::TEXT_FAINT,
                };
                let text = format!("[{}] {}: {}", entry.level, entry.target, entry.message);
                ui.add(
                    egui::Label::new(
                        egui::RichText::new(text)
                            .font(theme::mono(10.0))
                            .color(level_color),
                    )
                    .selectable(true)
                    .wrap_mode(egui::TextWrapMode::Extend),
                );
            }
        });

    bottom_border(ui, rect);
}

// ── ADVANCED rows ─────────────────────────────────────────────────────────────

fn config_folder_row(ui: &mut egui::Ui, state: &AppState) {
    let rect = row_rect(ui);
    ui.painter().text(
        Pos2::new(rect.left(), rect.top() + 10.0),
        Align2::LEFT_TOP,
        t!("settings.config_folder_title"),
        theme::body(12.5),
        theme::TEXT,
    );
    let config_unknown = t!("settings.unknown");
    let config_path = if state.config_dir.is_empty() {
        config_unknown.as_ref()
    } else {
        state.config_dir.as_str()
    };
    ui.painter().text(
        Pos2::new(rect.left(), rect.top() + 28.0),
        Align2::LEFT_TOP,
        config_path,
        theme::body(10.5),
        theme::TEXT_FAINT,
    );

    let btn_w = 72.0;
    let btn_rect = Rect::from_min_size(
        Pos2::new(rect.right() - btn_w, rect.top() + 10.0),
        Vec2::new(btn_w, 30.0),
    );
    let mut btn_ui = ui.new_child(egui::UiBuilder::new().max_rect(btn_rect).layout(
        egui::Layout::centered_and_justified(egui::Direction::LeftToRight),
    ));
    if widgets::button(
        &mut btn_ui,
        &t!("settings.open_external_button"),
        widgets::ButtonKind::Ghost,
        Vec2::new(btn_w, 30.0),
    )
    .clicked()
        && !state.config_dir.is_empty()
    {
        open_path(&state.config_dir);
    }

    bottom_border(ui, rect);
}

/// Spawn the platform file/URL opener for `p` on a detached thread so the UI
/// never blocks. Uses `explorer` on Windows, `open` on macOS, `xdg-open` elsewhere.
fn open_path(p: &str) {
    let p = p.to_string();
    std::thread::spawn(move || {
        let prog = if cfg!(target_os = "windows") {
            "explorer"
        } else if cfg!(target_os = "macos") {
            "open"
        } else {
            "xdg-open"
        };
        // `explorer` returns exit code 1 even on success, so we only log a hard
        // spawn failure and ignore the exit status itself.
        if let Err(e) = std::process::Command::new(prog).arg(&p).status() {
            log::warn!("{prog} {p} failed: {e}");
        }
    });
}

// ── DEBUG rows ────────────────────────────────────────────────────────────────

fn diagnostics_row(ui: &mut egui::Ui, cmd: &CommandTx, st: &mut SettingsUi) {
    let rect = row_rect(ui);
    ui.painter().text(
        Pos2::new(rect.left(), rect.top() + 10.0),
        Align2::LEFT_TOP,
        t!("settings.diagnostics_title"),
        theme::body(12.5),
        theme::TEXT,
    );
    ui.painter().text(
        Pos2::new(rect.left(), rect.top() + 28.0),
        Align2::LEFT_TOP,
        t!("settings.diagnostics_sub"),
        theme::body(10.5),
        theme::TEXT_FAINT,
    );

    let btn_w = 80.0_f32.max(
        ui.painter()
            .layout_no_wrap(
                t!("settings.open_button").to_string(),
                theme::body(11.5),
                theme::TEXT,
            )
            .size()
            .x
            + 20.0,
    );
    let btn_rect = Rect::from_min_size(
        Pos2::new(rect.right() - btn_w, rect.top() + 10.0),
        Vec2::new(btn_w, 30.0),
    );
    let mut btn_ui = ui.new_child(egui::UiBuilder::new().max_rect(btn_rect).layout(
        egui::Layout::centered_and_justified(egui::Direction::LeftToRight),
    ));
    if widgets::button(
        &mut btn_ui,
        &t!("settings.open_button"),
        widgets::ButtonKind::Ghost,
        Vec2::new(btn_w, 30.0),
    )
    .clicked()
    {
        crate::domain::actions::system::get_debug_info(cmd);
        st.modal = Some(Modal::Diagnostics);
    }
    bottom_border(ui, rect);
}

// ── ABOUT rows ────────────────────────────────────────────────────────────────

fn about_row(ui: &mut egui::Ui, st: &mut SettingsUi) {
    let rect = row_rect(ui);
    ui.painter().text(
        Pos2::new(rect.left(), rect.top() + 10.0),
        Align2::LEFT_TOP,
        halod_shared::app::APP_DISPLAY_NAME,
        theme::body(12.5),
        theme::TEXT,
    );
    ui.painter().text(
        Pos2::new(rect.left(), rect.top() + 28.0),
        Align2::LEFT_TOP,
        format!(
            "v{} {}",
            env!("CARGO_PKG_VERSION"),
            t!("settings.app_tagline")
        ),
        theme::body(10.5),
        theme::TEXT_FAINT,
    );

    right_button(ui, rect, &t!("settings.credits_button"), st, Modal::Credits);
    bottom_border(ui, rect);
}

fn third_party_row(ui: &mut egui::Ui, st: &mut SettingsUi) {
    let rect = row_rect(ui);
    ui.painter().text(
        Pos2::new(rect.left(), rect.top() + 10.0),
        Align2::LEFT_TOP,
        t!("settings.third_party_title"),
        theme::body(12.5),
        theme::TEXT,
    );
    ui.painter().text(
        Pos2::new(rect.left(), rect.top() + 28.0),
        Align2::LEFT_TOP,
        t!("settings.third_party_sub"),
        theme::body(10.5),
        theme::TEXT_FAINT,
    );

    right_button(ui, rect, &t!("settings.view_button"), st, Modal::Licenses);
    bottom_border(ui, rect);
}

const REPO_URL: &str = halod_shared::app::REPO_URL;

fn repo_row(ui: &mut egui::Ui) {
    let rect = row_rect(ui);
    let resp = ui.interact(rect, ui.id().with("repo_row"), Sense::click());
    ui.painter().text(
        Pos2::new(rect.left(), rect.top() + 10.0),
        Align2::LEFT_TOP,
        t!("settings.repository_title"),
        theme::body(12.5),
        theme::TEXT,
    );
    ui.painter().text(
        Pos2::new(rect.left(), rect.top() + 28.0),
        Align2::LEFT_TOP,
        REPO_URL.trim_start_matches("https://"),
        theme::body(10.5),
        if resp.hovered() {
            theme::CYAN
        } else {
            theme::TEXT_FAINT
        },
    );
    if resp.hovered() {
        ui.ctx().set_cursor_icon(egui::CursorIcon::PointingHand);
    }
    if resp.clicked() {
        open_path(REPO_URL);
    }
    bottom_border(ui, rect);
}

/// Parse `buf` as a u32 FPS value, falling back to `fallback`, clamped to 1–60.
fn parse_fps(buf: &str, fallback: u32) -> u32 {
    buf.parse::<u32>().unwrap_or(fallback).clamp(1, 60)
}

// ── Section header ────────────────────────────────────────────────────────────

fn section_header(ui: &mut egui::Ui, text: &str) {
    let (rect, _) = ui.allocate_exact_size(Vec2::new(ui.available_width(), 20.0), Sense::hover());
    ui.painter().text(
        Pos2::new(rect.left(), rect.center().y),
        Align2::LEFT_CENTER,
        text,
        theme::body(10.0),
        theme::TEXT_FAINT2,
    );
}

// ── Footer ────────────────────────────────────────────────────────────────────

fn footer(ui: &mut egui::Ui, _state: &AppState) {
    ui.label(
        egui::RichText::new(concat!(
            "HaloDaemon v",
            env!("CARGO_PKG_VERSION"),
            " · ",
            env!("HALOD_BUILD_HASH")
        ))
        .font(theme::body(11.0))
        .color(theme::TEXT_FAINT),
    );
}

// ── Modals ────────────────────────────────────────────────────────────────────

/// A shared modal window frame: dark bg overlay + centered popup card.
fn modal_frame<R>(
    ctx: &egui::Context,
    title: &str,
    st: &mut SettingsUi,
    default_w: f32,
    default_h: f32,
    body: impl FnOnce(&mut egui::Ui) -> R,
) {
    if widgets::modal_frame(ctx, "settings_modal", title, default_w, default_h, body) {
        st.modal = None;
    }
}

/// Third-party licenses modal — shows the full license text.
fn licenses_modal(ctx: &egui::Context, st: &mut SettingsUi) {
    modal_frame(
        ctx,
        &t!("settings.third_party_title"),
        st,
        640.0,
        540.0,
        |ui| {
            ui.label(
                egui::RichText::new(t!("settings.licenses_modal_body"))
                    .font(theme::body(12.0))
                    .color(theme::TEXT_MUT),
            );
            ui.add_space(10.0);
            egui::Frame::NONE
                .fill(theme::hex(0x080b10))
                .stroke(Stroke::new(1.0, theme::hex(0x1c2230)))
                .corner_radius(8.0)
                .inner_margin(egui::Margin::same(12))
                .show(ui, |ui| {
                    ui.label(
                        egui::RichText::new(THIRD_PARTY_LICENSES)
                            .font(theme::mono(10.5))
                            .color(theme::TEXT_DIM),
                    );
                });
        },
    );
}

/// Credits modal — shows the credits from the GTK about dialog.
fn credits_modal(ctx: &egui::Context, st: &mut SettingsUi) {
    modal_frame(ctx, &t!("settings.credits_title"), st, 420.0, 340.0, |ui| {
        ui.label(
            egui::RichText::new(halod_shared::app::APP_DISPLAY_NAME)
                .font(theme::bold(16.0))
                .color(theme::TEXT),
        );
        ui.label(
            egui::RichText::new(concat!("v", env!("CARGO_PKG_VERSION")))
                .font(theme::body(12.0))
                .color(theme::TEXT_MUT),
        );
        ui.add_space(8.0);
        ui.label(
            egui::RichText::new(format!(
                "{} {}",
                t!("settings.credits_developer"),
                halod_shared::app::AUTHOR
            ))
            .font(theme::body(12.0))
            .color(theme::TEXT_DIM),
        );
        ui.label(
            egui::RichText::new(format!(
                "{} GPL-3.0-or-later",
                t!("settings.credits_license")
            ))
            .font(theme::body(12.0))
            .color(theme::TEXT_DIM),
        );
        ui.hyperlink_to(
            egui::RichText::new(REPO_URL)
                .font(theme::body(12.0))
                .color(theme::CYAN),
            REPO_URL,
        );
        ui.add_space(16.0);

        ui.label(
            egui::RichText::new(t!("settings.acknowledgments"))
                .font(theme::semibold(13.0))
                .color(theme::TEXT),
        );
        ui.add_space(4.0);
        for (name, url) in &CREDIT_REFS {
            if url.is_empty() {
                ui.label(
                    egui::RichText::new(*name)
                        .font(theme::body(11.5))
                        .color(theme::TEXT_DIM),
                );
            } else {
                ui.hyperlink_to(
                    egui::RichText::new(*name)
                        .font(theme::body(11.5))
                        .color(theme::CYAN),
                    *url,
                )
                .on_hover_text(*url);
            }
        }
    });
}

/// Upstream projects credited in the Credits modal, mirroring the README
/// Acknowledgments table — `(name, url)`. An empty url renders as plain text
/// (no canonical repo link); a non-empty url renders as a clickable hyperlink.
const CREDIT_REFS: [(&str, &str); 11] = [
    ("Solaar", "https://github.com/pwr-Solaar/Solaar"),
    ("OpenRGB", "https://gitlab.com/CalcProgrammer1/OpenRGB"),
    ("liquidctl", "https://github.com/liquidctl/liquidctl"),
    (
        "Linux kernel nzxt-smart2",
        "https://github.com/torvalds/linux",
    ),
    (
        "LibreHardwareMonitor",
        "https://github.com/LibreHardwareMonitor/LibreHardwareMonitor",
    ),
    ("OpenRazer", "https://github.com/openrazer/openrazer"),
    (
        "linux-arctis-manager",
        "https://github.com/elegos/Linux-Arctis-Manager",
    ),
    ("sennheiser-gsx-control", ""),
    ("evnia", "https://github.com/tomasf/evnia"),
    ("g560-led", "https://github.com/mijoe/g560-led"),
    (
        "PawnIO modules",
        "https://github.com/namazso/PawnIO_modules",
    ),
];

/// Diagnostics modal — shows the full DebugInfo payload as formatted text.
fn diagnostics_modal(ctx: &egui::Context, debug: Option<&DebugInfo>, st: &mut SettingsUi) {
    modal_frame(
        ctx,
        &t!("settings.diagnostics_modal_title"),
        st,
        680.0,
        560.0,
        |ui| {
            match debug {
                None => {
                    ui.label(
                        egui::RichText::new(t!("settings.diagnostics_no_data"))
                            .font(theme::body(12.0))
                            .color(theme::TEXT_MUT),
                    );
                }
                Some(info) => {
                    // ── Copy / export ─────────────────────────────────────────
                    let copied_key = egui::Id::new("diag_copied_at");
                    ui.horizontal(|ui| {
                        if widgets::button(
                            ui,
                            &t!("settings.copy_json_button"),
                            widgets::ButtonKind::Ghost,
                            egui::vec2(110.0, 30.0),
                        )
                        .clicked()
                        {
                            ui.ctx().copy_text(diagnostics_json(info));
                            let now = ui.ctx().input(|i| i.time);
                            ui.ctx().data_mut(|d| d.insert_temp(copied_key, now));
                        }
                        ui.add_space(8.0);
                        if widgets::button(
                            ui,
                            &t!("settings.export_button"),
                            widgets::ButtonKind::Ghost,
                            egui::vec2(110.0, 30.0),
                        )
                        .clicked()
                        {
                            export_diagnostics(diagnostics_json(info));
                        }

                        let copied_at = ui.ctx().data(|d| d.get_temp::<f64>(copied_key));
                        let now = ui.ctx().input(|i| i.time);
                        if copied_feedback_visible(copied_at, now) {
                            ui.add_space(10.0);
                            ui.label(
                                egui::RichText::new(t!("settings.copied_feedback"))
                                    .font(theme::semibold(12.0))
                                    .color(theme::TRAFFIC_GREEN),
                            );
                            // Keep repainting so the confirmation clears without input.
                            ui.ctx().request_repaint();
                        }
                    });
                    ui.add_space(12.0);

                    // ── System ────────────────────────────────────────────────
                    section_label(ui, &t!("settings.diag_system"));
                    let sys = &info.system;
                    diag_card(ui, |ui| {
                        kv(ui, "OS", &format!("{:?} {}", sys.os, sys.os_version));
                        let elevated = if sys.running_elevated {
                            t!("settings.yes")
                        } else {
                            t!("settings.no")
                        };
                        kv(ui, &t!("settings.diag_elevated"), &elevated);
                        if let Some(p) = sys.pawnio_present {
                            let val = if p {
                                t!("settings.present")
                            } else {
                                t!("settings.absent")
                            };
                            kv(ui, "PawnIO", &val);
                        }
                        if let Some(u) = sys.udev_rules_present {
                            let val = if u {
                                t!("settings.present")
                            } else {
                                t!("settings.absent")
                            };
                            kv(ui, "udev rules", &val);
                        }
                        kv(ui, &t!("settings.diag_version"), &sys.daemon_version);
                        kv(ui, &t!("settings.diag_build"), &sys.daemon_build);
                    });

                    // ── Devices ───────────────────────────────────────────────
                    if !info.devices.is_empty() {
                        section_label(ui, &t!("settings.diag_devices", n = info.devices.len()));
                        diag_card(ui, |ui| {
                            for d in &info.devices {
                                let status = if d.connected {
                                    t!("settings.diag_connected")
                                } else {
                                    t!("settings.diag_offline")
                                };
                                mono_line(
                                    ui,
                                    &format!(
                                        "{} {} ({}) · {}",
                                        d.vendor, d.model, d.transport, status
                                    ),
                                    if d.connected {
                                        theme::TEXT
                                    } else {
                                        theme::OFFLINE_TEXT
                                    },
                                );
                                mono_line(ui, &format!("  {}", d.id), theme::TEXT_FAINT);
                                for (k, v) in &d.fields {
                                    mono_line(ui, &format!("    {k}: {v}"), theme::TEXT_DIM);
                                }
                            }
                        });
                    }

                    // ── HID entries ───────────────────────────────────────────
                    if !info.hid_entries.is_empty() {
                        section_label(ui, &t!("settings.diag_hid", n = info.hid_entries.len()));
                        diag_card(ui, |ui| {
                            for h in &info.hid_entries {
                                mono_line(
                                    ui,
                                    &format!(
                                        "{:04x}:{:04x}  page={:04x} usage={:04x}  {}",
                                        h.vid, h.pid, h.usage_page, h.usage, h.product
                                    ),
                                    theme::TEXT_DIM,
                                );
                            }
                        });
                    }

                    // ── SMBus buses ───────────────────────────────────────────
                    if !info.smbus_buses.is_empty() {
                        section_label(ui, &t!("settings.diag_smbus", n = info.smbus_buses.len()));
                        diag_card(ui, |ui| {
                            for b in &info.smbus_buses {
                                mono_line(
                                    ui,
                                    &format!(
                                        "Bus {} ({:?}): {}",
                                        b.bus_number, b.kind, b.adapter_name
                                    ),
                                    theme::TEXT_DIM,
                                );
                            }
                        });
                    }
                }
            }
        },
    );
}

/// A subtle inset panel wrapping one diagnostics section's rows.
fn diag_card<R>(ui: &mut egui::Ui, body: impl FnOnce(&mut egui::Ui) -> R) -> R {
    let r = egui::Frame::NONE
        .fill(theme::hex(0x080b10))
        .stroke(Stroke::new(1.0, theme::hex(0x1c2230)))
        .corner_radius(8.0)
        .inner_margin(egui::Margin::same(12))
        .show(ui, |ui| {
            ui.set_width(ui.available_width());
            body(ui)
        })
        .inner;
    ui.add_space(12.0);
    r
}

/// A label/value row inside a diagnostics card (mono value, right-aligned).
fn kv(ui: &mut egui::Ui, key: &str, value: &str) {
    widgets::value_row(ui, key, value, theme::TEXT_DIM);
}

/// A single monospace diagnostics line.
fn mono_line(ui: &mut egui::Ui, text: &str, color: Color32) {
    ui.label(
        egui::RichText::new(text)
            .font(theme::mono(10.5))
            .color(color),
    );
}

fn section_label(ui: &mut egui::Ui, text: &str) {
    ui.add_space(2.0);
    ui.label(
        egui::RichText::new(text)
            .font(theme::semibold(12.0))
            .color(theme::TEXT),
    );
    ui.add_space(6.0);
}

fn diagnostics_json(info: &DebugInfo) -> String {
    serde_json::to_string_pretty(info).unwrap_or_else(|e| format!("serialization error: {e}"))
}

const DIAGNOSTICS_FILENAME: &str = "halod-diagnostics.json";
const COPIED_FEEDBACK_SECS: f64 = 1.8;

pub(crate) fn copied_feedback_visible(copied_at: Option<f64>, now: f64) -> bool {
    copied_at.is_some_and(|at| now >= at && now - at < COPIED_FEEDBACK_SECS)
}

/// Open a save dialog and write `json` to the chosen file on a worker thread,
/// so the UI frame is never blocked by the native picker.
fn export_diagnostics(json: String) {
    std::thread::spawn(move || {
        if let Some(path) = rfd::FileDialog::new()
            .set_file_name(DIAGNOSTICS_FILENAME)
            .add_filter("JSON", &["json"])
            .save_file()
        {
            let _ = std::fs::write(path, json);
        }
    });
}

#[cfg(test)]
mod tests {
    use super::*;
    use halod_shared::types::DiscoveryStatus;

    #[test]
    fn scanning_only_during_discovering_phase() {
        let scanning = |phase| AppState {
            discovery: DiscoveryStatus {
                phase,
                ..Default::default()
            },
            ..Default::default()
        };
        assert!(is_scanning(&scanning(DiscoveryPhase::Discovering)));
        assert!(!is_scanning(&scanning(DiscoveryPhase::Idle)));
        assert!(!is_scanning(&scanning(DiscoveryPhase::Complete)));
        assert!(!is_scanning(&scanning(DiscoveryPhase::Error)));
    }

    /// Merge every `en` catalog file into the set of fully-qualified leaf keys
    /// it defines (mirrors how rust-i18n merges + flattens at load time).
    fn defined_en_keys() -> std::collections::BTreeSet<String> {
        fn flatten(
            prefix: &str,
            v: &serde_yaml::Value,
            out: &mut std::collections::BTreeSet<String>,
        ) {
            match v {
                serde_yaml::Value::Mapping(m) => {
                    for (k, val) in m {
                        let key = k.as_str().unwrap_or_default();
                        let path = if prefix.is_empty() {
                            key.to_string()
                        } else {
                            format!("{prefix}.{key}")
                        };
                        flatten(&path, val, out);
                    }
                }
                _ => {
                    out.insert(prefix.to_string());
                }
            }
        }
        let dir = format!("{}/locales", env!("CARGO_MANIFEST_DIR"));
        let mut out = std::collections::BTreeSet::new();
        for entry in std::fs::read_dir(&dir).unwrap() {
            let path = entry.unwrap().path();
            if path.extension().and_then(|e| e.to_str()) != Some("yaml") {
                continue;
            }
            let stem = path.file_stem().and_then(|s| s.to_str()).unwrap();
            if stem.split('.').next_back() != Some("en") {
                continue;
            }
            let v: serde_yaml::Value =
                serde_yaml::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
            flatten("", &v, &mut out);
        }
        out
    }

    /// Extract every STATIC translation key (a string-literal first argument to
    /// the `t!` macro) used across `src/**/*.rs`. Keys containing `{` are skipped
    /// — those are interpolation-only forms, i.e. plain format strings.
    fn used_static_keys() -> std::collections::BTreeSet<(String, String)> {
        fn walk(dir: &std::path::Path, files: &mut Vec<std::path::PathBuf>) {
            for e in std::fs::read_dir(dir).unwrap() {
                let p = e.unwrap().path();
                if p.is_dir() {
                    walk(&p, files);
                } else if p.extension().and_then(|x| x.to_str()) == Some("rs") {
                    files.push(p);
                }
            }
        }
        let src = format!("{}/src", env!("CARGO_MANIFEST_DIR"));
        let mut files = Vec::new();
        walk(std::path::Path::new(&src), &mut files);

        let mut out = std::collections::BTreeSet::new();
        for f in files {
            let text = std::fs::read_to_string(&f).unwrap();
            let bytes = text.as_bytes();
            let mut i = 0;
            while let Some(rel) = text[i..].find("t!(") {
                let start = i + rel;
                i = start + 3;
                // Require a non-identifier char before `t!(` (else it's the tail
                // of `format!(`, `write!(`, etc.).
                if start > 0 {
                    let prev = bytes[start - 1];
                    if prev.is_ascii_alphanumeric() || prev == b'_' {
                        continue;
                    }
                }
                let rest = text[i..].trim_start();
                if let Some(after_quote) = rest.strip_prefix('"') {
                    if let Some(end) = after_quote.find('"') {
                        let key = &after_quote[..end];
                        // Static keys only; a `%{` placeholder means the value,
                        // not the key, interpolates — keys never contain `{`.
                        if !key.contains('{') {
                            out.insert((key.to_string(), f.display().to_string()));
                        }
                    }
                }
            }
        }
        out
    }

    #[test]
    fn every_used_translation_key_is_defined() {
        // A translation whose key is absent from the catalog renders the raw key
        // path to the user instead of copy — this guards against that silent
        // fallback across the whole GUI.
        let defined = defined_en_keys();
        let missing: Vec<_> = used_static_keys()
            .into_iter()
            .filter(|(k, _)| !defined.contains(k))
            .collect();
        assert!(
            missing.is_empty(),
            "translation keys used in code but missing from the en catalog: {missing:#?}"
        );
    }

    #[test]
    fn credit_refs_are_well_formed_and_unique() {
        let mut seen = std::collections::HashSet::new();
        for (name, url) in &CREDIT_REFS {
            assert!(!name.trim().is_empty(), "credit name must not be empty");
            assert!(seen.insert(*name), "duplicate credit entry: {name}");
            assert!(
                url.is_empty() || url.starts_with("https://"),
                "{name} url must be empty or https: {url:?}"
            );
        }
    }

    #[test]
    fn start_on_boot_cache_follows_write_result() {
        // Success adopts the new value; failure keeps the prior cache.
        assert_eq!(cache_after_toggle(Some(false), true, true), Some(true));
        assert_eq!(cache_after_toggle(Some(false), true, false), Some(false));
        assert_eq!(cache_after_toggle(Some(true), false, true), Some(false));
        assert_eq!(cache_after_toggle(Some(true), false, false), Some(true));
    }

    #[test]
    fn languages_match_shared_supported_set() {
        // The GUI's display table and the daemon's accepted set must agree, or a
        // selectable language would be rejected by the daemon (or vice versa).
        let ui_codes: Vec<&str> = LANGUAGES.iter().map(|(c, _)| *c).collect();
        assert_eq!(ui_codes, halod_shared::types::SUPPORTED_LANGUAGES);
        for (_, name) in LANGUAGES {
            assert!(!name.trim().is_empty());
        }
    }

    #[test]
    fn language_display_falls_back_to_code() {
        assert_eq!(language_display("en"), "English");
        assert_eq!(language_display("xx"), "xx");
    }

    #[test]
    fn catalogs_have_identical_key_trees() {
        // Every language must define the same keys as English, else `t!`
        // silently falls back and strings drift untranslated. Catalogs are split
        // across per-screen files (`<ns>.<code>.yaml`, plus the base
        // `<code>.yaml`); rust-i18n derives the locale from the LAST dotted
        // filename segment and merges them, so this test merges the same way.
        use std::collections::{BTreeMap, BTreeSet};
        fn flatten(prefix: &str, v: &serde_yaml::Value, out: &mut BTreeSet<String>) {
            match v {
                serde_yaml::Value::Mapping(m) => {
                    for (k, val) in m {
                        let key = k.as_str().unwrap_or_default();
                        let path = if prefix.is_empty() {
                            key.to_string()
                        } else {
                            format!("{prefix}.{key}")
                        };
                        flatten(&path, val, out);
                    }
                }
                _ => {
                    out.insert(prefix.to_string());
                }
            }
        }
        let dir = format!("{}/locales", env!("CARGO_MANIFEST_DIR"));
        let mut per_locale: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
        for entry in std::fs::read_dir(&dir).expect("locales dir") {
            let path = entry.unwrap().path();
            if path.extension().and_then(|e| e.to_str()) != Some("yaml") {
                continue;
            }
            let stem = path.file_stem().and_then(|s| s.to_str()).unwrap();
            let locale = stem.split('.').next_back().unwrap().to_string();
            let text = std::fs::read_to_string(&path).unwrap();
            let v: serde_yaml::Value = serde_yaml::from_str(&text).expect("valid yaml");
            flatten("", &v, per_locale.entry(locale).or_default());
        }
        let en = per_locale.get("en").expect("en catalog").clone();
        assert!(!en.is_empty(), "en catalog has no keys");
        for (code, _) in LANGUAGES.iter().filter(|(c, _)| *c != "en") {
            let other = per_locale.get(*code).cloned().unwrap_or_default();
            assert_eq!(
                en,
                other,
                "{code} key tree differs from en (missing: {:?}, extra: {:?})",
                en.difference(&other).collect::<Vec<_>>(),
                other.difference(&en).collect::<Vec<_>>(),
            );
        }
    }

    #[test]
    fn parse_fps_clamps_and_falls_back() {
        assert_eq!(parse_fps("30", 24), 30);
        assert_eq!(parse_fps("0", 24), 1);
        assert_eq!(parse_fps("120", 24), 60);
        assert_eq!(parse_fps("", 24), 24);
        assert_eq!(parse_fps("abc", 24), 24);
    }

    #[test]
    fn diagnostics_json_round_trips_debug_info() {
        use halod_shared::debug_info::{OsKind, SystemDebugInfo};
        let info = DebugInfo {
            system: SystemDebugInfo {
                os: OsKind::Windows,
                os_version: "10.0.26200".into(),
                running_elevated: true,
                pawnio_present: Some(true),
                udev_rules_present: None,
                daemon_version: "1.2.3".into(),
                daemon_build: "halod +default".into(),
            },
            devices: vec![],
            hid_entries: vec![],
            smbus_buses: vec![],
            dependencies: vec![],
        };
        let json = diagnostics_json(&info);
        // Pretty-printed (multi-line) and parses back to an equal snapshot.
        assert!(json.contains('\n'));
        let back: DebugInfo = serde_json::from_str(&json).unwrap();
        assert_eq!(back.system.os_version, "10.0.26200");
        assert_eq!(back.system.daemon_version, "1.2.3");
        assert!(back.system.running_elevated);
    }

    #[test]
    fn copied_feedback_visible_within_window_only() {
        // Never copied.
        assert!(!copied_feedback_visible(None, 5.0));
        // Just copied.
        assert!(copied_feedback_visible(Some(5.0), 5.0));
        // Inside the window.
        assert!(copied_feedback_visible(
            Some(5.0),
            5.0 + COPIED_FEEDBACK_SECS - 0.1
        ));
        // Past the window.
        assert!(!copied_feedback_visible(
            Some(5.0),
            5.0 + COPIED_FEEDBACK_SECS + 0.1
        ));
        // Clock ran backwards (stale timestamp from a previous session/reset).
        assert!(!copied_feedback_visible(Some(5.0), 4.0));
    }
}
