// SPDX-License-Identifier: GPL-3.0-or-later
//! Canonical HaloDaemon plugin-repository index, hashing, and signature logic.

use std::collections::HashSet;
use std::fs;
use std::io::Write;
use std::path::{Component, Path, PathBuf};

use anyhow::{anyhow, bail, Context, Result};
use base64::{engine::general_purpose::STANDARD as B64, Engine as _};
use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

pub const REPOSITORY_SCHEMA: u32 = 1;
pub const SIGNATURE_ALGORITHM: &str = "ed25519";
pub const GENERATED_HEADER: &str = "# SPDX-License-Identifier: GPL-3.0-or-later\n# Generated by halod-plugin-signing. Do not edit package hashes manually.\n";

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RepositoryManifest {
    pub schema: u32,
    pub id: String,
    pub name: String,
    pub version: String,
    pub compatibility: RepositoryCompatibility,
    pub packages: Vec<RepositoryPackage>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RepositoryCompatibility {
    pub halod: String,
    pub plugin_api: u32,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RepositoryPackage {
    pub id: String,
    pub path: PathBuf,
    pub version: String,
    pub sha256: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RepositorySignature {
    pub schema: u32,
    pub algorithm: String,
    pub key_id: String,
    pub signature: String,
}

#[derive(Debug, Deserialize)]
struct PackageMeta {
    id: String,
    version: String,
    #[serde(flatten)]
    _rest: serde_yaml::Value,
}

pub fn read_repository_index(repo_dir: &Path) -> Result<RepositoryManifest> {
    let manifest = parse_repository_index(repo_dir)?;
    validate_repository_index(&manifest)?;
    Ok(manifest)
}

fn parse_repository_index(repo_dir: &Path) -> Result<RepositoryManifest> {
    let path = repo_dir.join("repository.yaml");
    let bytes = fs::read(&path).with_context(|| format!("reading {}", path.display()))?;
    serde_yaml::from_slice(&bytes).with_context(|| format!("parsing {}", path.display()))
}

pub fn validate_repository_index(manifest: &RepositoryManifest) -> Result<()> {
    if manifest.schema != REPOSITORY_SCHEMA {
        bail!("unsupported repository manifest schema {}", manifest.schema);
    }
    validate_identifier("repository id", &manifest.id)?;
    if manifest.name.trim().is_empty() {
        bail!("repository name must be non-empty");
    }
    validate_repository_version(&manifest.version)?;
    semver::VersionReq::parse(&manifest.compatibility.halod)
        .context("parsing repository compatibility.halod")?;

    let mut ids = HashSet::new();
    let mut paths = HashSet::new();
    for package in &manifest.packages {
        validate_identifier("repository package id", &package.id)?;
        semver::Version::parse(&package.version)
            .with_context(|| format!("parsing package '{}' version", package.id))?;
        let normalized = normalized_relative_path(&package.path)?;
        if !ids.insert(package.id.as_str()) {
            bail!(
                "repository package id '{}' is declared more than once",
                package.id
            );
        }
        if !paths.insert(normalized.clone()) {
            bail!("repository package path '{normalized}' is declared more than once");
        }
        if package.sha256.len() != 64
            || !package.sha256.bytes().all(|byte| byte.is_ascii_hexdigit())
        {
            bail!(
                "repository package '{}' has an invalid sha256 digest",
                package.id
            );
        }
    }
    Ok(())
}

pub fn validate_compatibility(
    manifest: &RepositoryManifest,
    halod_version: &str,
    plugin_api: u32,
) -> Result<()> {
    if manifest.compatibility.plugin_api != plugin_api {
        bail!(
            "repository requires plugin API {}, but Halo supports {}",
            manifest.compatibility.plugin_api,
            plugin_api
        );
    }
    let requirement = semver::VersionReq::parse(&manifest.compatibility.halod)
        .context("parsing repository compatibility.halod")?;
    let current = semver::Version::parse(halod_version).context("parsing Halo package version")?;
    if !requirement.matches(&current) {
        bail!(
            "repository requires Halo '{}', current Halo is {}",
            manifest.compatibility.halod,
            current
        );
    }
    Ok(())
}

pub fn validate_repository_packages(repo_dir: &Path, manifest: &RepositoryManifest) -> Result<()> {
    validate_repository_index(manifest)?;
    for package in &manifest.packages {
        let dir = repo_dir.join(&package.path);
        if !dir.is_dir() {
            bail!(
                "repository package '{}' directory is missing: {}",
                package.id,
                dir.display()
            );
        }
        reject_symlinks(&dir)
            .with_context(|| format!("checking package '{}' for symlinks", package.id))?;
        let meta = read_package_meta(&dir)
            .with_context(|| format!("reading package '{}' manifest", package.id))?;
        if meta.id != package.id {
            bail!(
                "repository package '{}' does not match its plugin.yaml id",
                package.id
            );
        }
        if meta.version != package.version {
            bail!(
                "repository package '{}' does not match its plugin.yaml version",
                package.id
            );
        }
        let actual = package_hash(&dir)
            .with_context(|| format!("hashing repository package '{}'", package.id))?;
        if !actual.eq_ignore_ascii_case(&package.sha256) {
            bail!(
                "package '{}' hash mismatch: expected {}, got {}",
                package.id,
                package.sha256,
                actual
            );
        }
    }
    Ok(())
}

/// Validate the complete repository without writing: structural metadata,
/// one-to-one top-level package discovery, identity/version, and package hash.
pub fn validate_repository(repo_dir: &Path, manifest: &RepositoryManifest) -> Result<()> {
    validate_repository_packages(repo_dir, manifest)?;
    let discovered = discover_packages(repo_dir)?;
    if discovered != manifest.packages {
        let indexed: Vec<_> = manifest
            .packages
            .iter()
            .map(|package| &package.id)
            .collect();
        let actual: Vec<_> = discovered.iter().map(|package| &package.id).collect();
        bail!("repository package index is stale (indexed: {indexed:?}, discovered: {actual:?})");
    }
    Ok(())
}

/// Discover top-level package directories and calculate their canonical hashes.
pub fn discover_packages(repo_dir: &Path) -> Result<Vec<RepositoryPackage>> {
    reject_symlinks(repo_dir)?;
    let mut packages = Vec::new();
    for entry in
        fs::read_dir(repo_dir).with_context(|| format!("reading {}", repo_dir.display()))?
    {
        let entry = entry?;
        let file_type = entry.file_type()?;
        if !file_type.is_dir() || entry.file_name() == ".git" {
            continue;
        }
        let dir = entry.path();
        if !dir.join("plugin.yaml").is_file() {
            continue;
        }
        let path = PathBuf::from(
            entry
                .file_name()
                .to_str()
                .ok_or_else(|| anyhow!("package directory name is not UTF-8"))?,
        );
        let meta = read_package_meta(&dir)?;
        let directory = normalized_relative_path(&path)?;
        if meta.id != directory {
            bail!(
                "package directory '{}' does not match plugin.yaml id '{}'",
                directory,
                meta.id
            );
        }
        validate_identifier("plugin id", &meta.id)?;
        semver::Version::parse(&meta.version)
            .with_context(|| format!("parsing package '{}' version", meta.id))?;
        packages.push(RepositoryPackage {
            id: meta.id,
            path,
            version: meta.version,
            sha256: package_hash(&dir)?,
        });
    }
    packages.sort_by(|left, right| left.id.as_bytes().cmp(right.id.as_bytes()));
    let mut ids = HashSet::new();
    for package in &packages {
        if !ids.insert(package.id.as_str()) {
            bail!("plugin id '{}' was discovered more than once", package.id);
        }
    }
    Ok(packages)
}

pub fn generated_manifest(
    repo_dir: &Path,
    current: &RepositoryManifest,
    version: Option<&str>,
) -> Result<RepositoryManifest> {
    let mut generated = current.clone();
    if let Some(version) = version {
        validate_repository_version(version).context("parsing requested repository version")?;
        generated.version = version.to_owned();
    }
    generated.packages = discover_packages(repo_dir)?;
    validate_repository_index(&generated)?;
    Ok(generated)
}

pub fn canonical_index_bytes(manifest: &RepositoryManifest) -> Result<Vec<u8>> {
    validate_repository_index(manifest)?;
    let mut out = String::from(GENERATED_HEADER);
    out.push_str(&format!(
        "schema: {}\nid: {}\nname: {}\nversion: {}\n\ncompatibility:\n  halod: {}\n  plugin_api: {}\n\npackages:\n",
        manifest.schema,
        yaml_string(&manifest.id),
        yaml_string(&manifest.name),
        yaml_string(&manifest.version),
        yaml_string(&manifest.compatibility.halod),
        manifest.compatibility.plugin_api
    ));
    let mut packages = manifest.packages.clone();
    packages.sort_by(|left, right| left.id.as_bytes().cmp(right.id.as_bytes()));
    for package in packages {
        out.push_str(&format!(
            "  - id: {}\n    path: {}\n    version: {}\n    sha256: {}\n",
            yaml_string(&package.id),
            yaml_string(&normalized_relative_path(&package.path)?),
            yaml_string(&package.version),
            package.sha256.to_ascii_lowercase()
        ));
    }
    Ok(out.into_bytes())
}

pub fn rewrite_index(repo_dir: &Path, version: Option<&str>, check: bool) -> Result<bool> {
    // Generation replaces the package list, so it can repair malformed or
    // stale digest fields in the current generated section.
    let current = parse_repository_index(repo_dir)?;
    let generated = generated_manifest(repo_dir, &current, version)?;
    let expected = canonical_index_bytes(&generated)?;
    let path = repo_dir.join("repository.yaml");
    let actual = fs::read(&path).with_context(|| format!("reading {}", path.display()))?;
    if actual == expected {
        return Ok(false);
    }
    if check {
        bail!("{} is not the canonical generated index", path.display());
    }
    atomic_write(&path, &expected)?;
    Ok(true)
}

/// Deterministic SHA-256 over sorted UTF-8 forward-slash relative paths,
/// file lengths, and bytes. Symlinks and non-UTF-8 paths are rejected.
pub fn package_hash(package_dir: &Path) -> Result<String> {
    reject_symlinks(package_dir)?;
    let mut files = Vec::new();
    collect_package_files(package_dir, package_dir, &mut files)?;
    files.sort_by(|left, right| left.0.as_bytes().cmp(right.0.as_bytes()));
    let mut hasher = Sha256::new();
    for (relative, path) in files {
        let bytes = fs::read(&path).with_context(|| format!("reading package file {relative}"))?;
        hasher.update(relative.as_bytes());
        hasher.update([0]);
        hasher.update((bytes.len() as u64).to_le_bytes());
        hasher.update(&bytes);
    }
    Ok(format!("{:x}", hasher.finalize()))
}

pub fn signature_bytes(key_id: &str, signature: &[u8; 64]) -> Vec<u8> {
    format!(
        "schema: {REPOSITORY_SCHEMA}\nalgorithm: {SIGNATURE_ALGORITHM}\nkey_id: {key_id}\nsignature: {}\n",
        B64.encode(signature)
    )
    .into_bytes()
}

pub fn verify_signature(
    payload: &[u8],
    signature_bytes: &[u8],
    trusted_keys: &[(&str, &str)],
) -> Result<()> {
    let signature: RepositorySignature =
        serde_yaml::from_slice(signature_bytes).context("parsing repository signature")?;
    if signature.schema != REPOSITORY_SCHEMA {
        bail!(
            "unsupported repository signature schema {}",
            signature.schema
        );
    }
    if signature.algorithm != SIGNATURE_ALGORITHM {
        bail!(
            "unsupported repository signature algorithm '{}'",
            signature.algorithm
        );
    }
    let key_b64 = trusted_keys
        .iter()
        .find_map(|(id, key)| (*id == signature.key_id).then_some(*key))
        .ok_or_else(|| anyhow!("unknown repository signing key '{}'", signature.key_id))?;
    let public: [u8; 32] = decode_array(key_b64, "repository public key")?;
    let raw_signature: [u8; 64] = decode_array(&signature.signature, "repository signature")?;
    let key = VerifyingKey::from_bytes(&public).context("constructing repository verifying key")?;
    key.verify(payload, &Signature::from_bytes(&raw_signature))
        .map_err(|_| anyhow!("repository signature does not match repository.yaml"))
}

pub fn reject_symlinks(root: &Path) -> Result<()> {
    for entry in fs::read_dir(root).with_context(|| format!("reading {}", root.display()))? {
        let entry = entry?;
        let file_type = entry.file_type()?;
        if file_type.is_symlink() {
            bail!("repo contains a symlink: {}", entry.path().display());
        }
        if file_type.is_dir() && entry.file_name() != ".git" {
            reject_symlinks(&entry.path())?;
        }
    }
    Ok(())
}

fn read_package_meta(package_dir: &Path) -> Result<PackageMeta> {
    let path = package_dir.join("plugin.yaml");
    let bytes = fs::read(&path).with_context(|| format!("reading {}", path.display()))?;
    serde_yaml::from_slice(&bytes).with_context(|| format!("parsing {}", path.display()))
}

fn validate_identifier(label: &str, value: &str) -> Result<()> {
    if value.is_empty()
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-'))
    {
        bail!("{label} '{value}' must contain only ASCII letters, digits, '_' or '-'");
    }
    Ok(())
}

fn validate_repository_version(value: &str) -> Result<()> {
    if semver::Version::parse(value).is_ok() {
        return Ok(());
    }
    let calendar = value.split('.').collect::<Vec<_>>();
    if calendar.len() == 3
        && calendar
            .iter()
            .all(|part| !part.is_empty() && part.bytes().all(|byte| byte.is_ascii_digit()))
    {
        return Ok(());
    }
    bail!("repository version '{value}' is not semver or a numeric calendar version")
}

fn normalized_relative_path(path: &Path) -> Result<String> {
    if path.is_absolute() || path.as_os_str().is_empty() {
        bail!("invalid repository-relative path '{}'", path.display());
    }
    let mut parts = Vec::new();
    for component in path.components() {
        match component {
            Component::Normal(part) => parts.push(
                part.to_str()
                    .ok_or_else(|| anyhow!("path '{}' is not UTF-8", path.display()))?,
            ),
            _ => bail!("invalid repository-relative path '{}'", path.display()),
        }
    }
    Ok(parts.join("/"))
}

fn collect_package_files(
    root: &Path,
    current: &Path,
    out: &mut Vec<(String, PathBuf)>,
) -> Result<()> {
    for entry in fs::read_dir(current).with_context(|| format!("reading {}", current.display()))? {
        let entry = entry?;
        let file_type = entry.file_type()?;
        if file_type.is_symlink() {
            bail!("package contains a symlink: {}", entry.path().display());
        }
        if file_type.is_dir() {
            collect_package_files(root, &entry.path(), out)?;
        } else if file_type.is_file() {
            let relative = entry
                .path()
                .strip_prefix(root)
                .expect("walk remains under root")
                .to_owned();
            out.push((normalized_relative_path(&relative)?, entry.path()));
        } else {
            bail!(
                "package contains a non-regular file: {}",
                entry.path().display()
            );
        }
    }
    Ok(())
}

fn yaml_string(value: &str) -> String {
    // JSON strings are valid YAML scalars and give deterministic escaping.
    serde_yaml::to_string(value)
        .expect("serializing a string cannot fail")
        .trim()
        .trim_start_matches("---\n")
        .to_owned()
}

fn decode_array<const N: usize>(value: &str, label: &str) -> Result<[u8; N]> {
    B64.decode(value.trim())
        .with_context(|| format!("decoding {label}"))?
        .try_into()
        .map_err(|_| anyhow!("{label} is not {N} bytes"))
}

fn atomic_write(path: &Path, bytes: &[u8]) -> Result<()> {
    let parent = path.parent().unwrap_or_else(|| Path::new("."));
    let mut temp = tempfile::NamedTempFile::new_in(parent)
        .with_context(|| format!("creating temporary file beside {}", path.display()))?;
    temp.write_all(bytes)?;
    temp.as_file().sync_all()?;
    temp.persist(path)
        .map_err(|error| error.error)
        .with_context(|| format!("replacing {}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn package(root: &Path, id: &str, version: &str) -> PathBuf {
        let dir = root.join(id);
        fs::create_dir_all(&dir).unwrap();
        fs::write(
            dir.join("plugin.yaml"),
            format!("id: {id}\nversion: {version}\n"),
        )
        .unwrap();
        fs::write(dir.join("main.lua"), "return {}\n").unwrap();
        dir
    }

    #[test]
    fn package_hash_changes_for_name_length_and_contents() {
        let root = tempfile::tempdir().unwrap();
        let dir = package(root.path(), "demo", "1.0.0");
        let original = package_hash(&dir).unwrap();
        fs::write(dir.join("main.lua"), "return {x=1}\n").unwrap();
        assert_ne!(original, package_hash(&dir).unwrap());
        fs::rename(dir.join("main.lua"), dir.join("renamed.lua")).unwrap();
        let renamed = package_hash(&dir).unwrap();
        assert_ne!(original, renamed);
        fs::write(dir.join("renamed.lua"), "return {x=10}\n").unwrap();
        assert_ne!(renamed, package_hash(&dir).unwrap());
    }

    #[test]
    fn generated_index_is_sorted_lf_terminated_and_checkable() {
        let root = tempfile::tempdir().unwrap();
        package(root.path(), "zeta", "1.0.0");
        package(root.path(), "alpha", "2.0.0");
        let initial = RepositoryManifest {
            schema: 1,
            id: "test-repo".into(),
            name: "Test repository".into(),
            version: "1.0.0".into(),
            compatibility: RepositoryCompatibility {
                halod: ">=0.2.0, <0.3.0".into(),
                plugin_api: 1,
            },
            packages: vec![],
        };
        fs::write(
            root.path().join("repository.yaml"),
            canonical_index_bytes(&initial).unwrap(),
        )
        .unwrap();
        assert!(rewrite_index(root.path(), Some("2026.7.1"), false).unwrap());
        assert!(!rewrite_index(root.path(), None, true).unwrap());
        let bytes = fs::read(root.path().join("repository.yaml")).unwrap();
        assert!(bytes.ends_with(b"\n"));
        assert!(!bytes.contains(&b'\r'));
        let text = String::from_utf8(bytes).unwrap();
        assert!(text.find("alpha").unwrap() < text.find("zeta").unwrap());

        let manifest = read_repository_index(root.path()).unwrap();
        let stale = text.replacen(&manifest.packages[0].sha256, "not-a-digest", 1);
        fs::write(root.path().join("repository.yaml"), stale).unwrap();
        assert!(rewrite_index(root.path(), None, false).unwrap());
        validate_repository(root.path(), &read_repository_index(root.path()).unwrap()).unwrap();
    }

    #[test]
    fn signature_verification_rejects_any_payload_change() {
        use ed25519_dalek::{Signer, SigningKey};
        let seed = [7_u8; 32];
        let key = SigningKey::from_bytes(&seed);
        let payload = b"schema: 1\n";
        let signature = key.sign(payload).to_bytes();
        let document = signature_bytes("test", &signature);
        let public = B64.encode(key.verifying_key().to_bytes());
        verify_signature(payload, &document, &[("test", &public)]).unwrap();
        assert!(verify_signature(b"schema: 2\n", &document, &[("test", &public)]).is_err());
    }
}
