// SPDX-License-Identifier: GPL-3.0-or-later
//! Canonical HaloDaemon plugin-repository index, hashing, and signature logic.

use std::collections::HashSet;
use std::fs;
use std::io::{Read, Write};
use std::path::{Component, Path, PathBuf};

use anyhow::{anyhow, bail, Context, Result};
use base64::{engine::general_purpose::STANDARD as B64, Engine as _};
use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

pub const REPOSITORY_SCHEMA: u32 = 1;
/// Lua host/plugin ABI supported by HaloDaemon and its repository tooling.
/// Keep this value here so the daemon and standalone release tool cannot drift.
pub const PLUGIN_API: u32 = 2;
pub const SIGNATURE_ALGORITHM: &str = "ed25519";
pub const BUNDLE_METADATA_PATH: &str = ".halod-plugin-bundle.yaml";
const BUNDLE_MAGIC: &[u8] = b"HALODPLUG1\n";
pub const GENERATED_HEADER: &str = concat!(
    "# SPDX-License-",
    "Identifier: GPL-3.0-or-later\n",
    "# Generated by halod-plugin-signing. Do not edit package hashes manually.\n"
);

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PackageHashMismatch {
    pub package: String,
    pub expected: String,
    pub actual: String,
}

impl std::fmt::Display for PackageHashMismatch {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "package '{}' hash mismatch: expected {}, got {}",
            self.package, self.expected, self.actual
        )
    }
}

impl std::error::Error for PackageHashMismatch {}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PackageManifestMismatch {
    pub package: String,
    pub field: String,
    pub expected: String,
    pub actual: String,
}

impl std::fmt::Display for PackageManifestMismatch {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "repository package '{}' does not match its plugin.yaml {}: expected {}, got {}",
            self.package, self.field, self.expected, self.actual
        )
    }
}

impl std::error::Error for PackageManifestMismatch {}

/// Detached signature verification failed. Its stable type lets IPC clients
/// localize the user-facing error while logs retain the precise diagnostic.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RepositorySignatureMismatch;

impl std::fmt::Display for RepositorySignatureMismatch {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("repository signature does not match repository.yaml")
    }
}

impl std::error::Error for RepositorySignatureMismatch {}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RepositoryManifest {
    pub schema: u32,
    pub id: String,
    pub name: String,
    pub version: String,
    #[serde(default)]
    pub licenses_sha256: Option<String>,
    /// Optional publisher identity. On first import Halo verifies the detached
    /// signature with this key and pins it for all later revisions (TOFU).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub signing_key: Option<RepositorySigningKey>,
    pub compatibility: RepositoryCompatibility,
    pub packages: Vec<RepositoryPackage>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RepositorySigningKey {
    pub id: String,
    pub algorithm: String,
    pub public_key: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RepositoryCompatibility {
    pub halod: String,
    pub plugin_api: u32,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RepositoryPackage {
    pub id: String,
    pub path: PathBuf,
    pub version: String,
    pub sha256: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RepositorySignature {
    pub schema: u32,
    pub algorithm: String,
    pub key_id: String,
    pub signature: String,
}

/// Provenance stored alongside a deterministic embedded repository snapshot.
/// The commit is informational and is used as the immutable revision id after
/// extraction; repository.yaml and repository.sig remain the authority for
/// executable package integrity.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BundleMetadata {
    pub commit: String,
    pub repository_id: String,
    pub repository_version: String,
}

/// Produce a deterministic tar archive suitable for embedding in a Halo
/// release. The complete REUSE licensing material travels with the scripts.
pub fn write_bundle(repo_dir: &Path, commit: &str, output: &Path) -> Result<BundleMetadata> {
    if commit.len() != 40 || !commit.bytes().all(|b| b.is_ascii_hexdigit()) {
        bail!("bundle commit must be a 40-character hexadecimal SHA");
    }
    let manifest = read_repository_index(repo_dir)?;
    validate_repository(repo_dir, &manifest)?;
    reject_symlinks(repo_dir)?;
    if !repo_dir.join("repository.sig").is_file() {
        bail!("repository.sig is missing");
    }
    let metadata = BundleMetadata {
        commit: commit.to_ascii_lowercase(),
        repository_id: manifest.id.clone(),
        repository_version: manifest.version.clone(),
    };
    let mut paths = Vec::new();
    collect_bundle_paths(repo_dir, repo_dir, &mut paths)?;
    paths.sort();
    let parent = output.parent().unwrap_or_else(|| Path::new("."));
    let mut temp = tempfile::NamedTempFile::new_in(parent)?;
    let writer = temp.as_file_mut();
    writer.write_all(BUNDLE_MAGIC)?;
    append_bundle_file(
        writer,
        Path::new(BUNDLE_METADATA_PATH),
        serde_yaml::to_string(&metadata)?.as_bytes(),
    )?;
    for relative in paths {
        let bytes = fs::read(repo_dir.join(&relative))?;
        append_bundle_file(writer, &relative, &bytes)?;
    }
    writer.write_all(&0_u32.to_be_bytes())?;
    temp.as_file().sync_all()?;
    temp.persist(output).map_err(|error| error.error)?;
    Ok(metadata)
}

/// Extract a bundle without permitting archive path traversal, links, device
/// nodes, or oversized entries. The caller validates the resulting repository
/// before atomically activating it.
pub fn extract_bundle(bytes: &[u8], destination: &Path) -> Result<BundleMetadata> {
    if destination.exists() {
        bail!(
            "bundle destination already exists: {}",
            destination.display()
        );
    }
    fs::create_dir_all(destination)?;
    let mut metadata = None;
    let mut cursor = std::io::Cursor::new(bytes);
    let mut magic = vec![0; BUNDLE_MAGIC.len()];
    cursor.read_exact(&mut magic)?;
    if magic != BUNDLE_MAGIC {
        bail!("bundle has an unknown format");
    }
    loop {
        let mut length = [0_u8; 4];
        cursor.read_exact(&mut length)?;
        let length = u32::from_be_bytes(length) as usize;
        if length == 0 {
            break;
        }
        if length > 4096 {
            bail!("bundle path is too long");
        }
        let mut path = vec![0; length];
        cursor.read_exact(&mut path)?;
        let path = std::str::from_utf8(&path).context("bundle path is not UTF-8")?;
        let normalized = normalized_relative_path(Path::new(path))?;
        let mut size = [0_u8; 8];
        cursor.read_exact(&mut size)?;
        let size = u64::from_be_bytes(size);
        if size > 64 * 1024 * 1024 {
            bail!("bundle entry is too large: {normalized}");
        }
        let mut content = vec![0; size as usize];
        cursor.read_exact(&mut content)?;
        let target = destination.join(&normalized);
        if let Some(parent) = target.parent() {
            fs::create_dir_all(parent)?;
        }
        if normalized == BUNDLE_METADATA_PATH {
            metadata = Some(serde_yaml::from_slice(&content).context("parsing bundle metadata")?);
        } else {
            fs::write(target, content)?;
        }
    }
    let metadata: BundleMetadata = metadata.ok_or_else(|| anyhow!("bundle metadata is missing"))?;
    if metadata.commit.len() != 40 || !metadata.commit.bytes().all(|b| b.is_ascii_hexdigit()) {
        bail!("bundle metadata has an invalid commit SHA");
    }
    Ok(metadata)
}

fn collect_bundle_paths(root: &Path, current: &Path, out: &mut Vec<PathBuf>) -> Result<()> {
    for entry in fs::read_dir(current)? {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;
        if entry.file_name() == ".git" {
            continue;
        }
        if file_type.is_symlink() {
            bail!("repository contains a symlink: {}", path.display());
        }
        if file_type.is_dir() {
            collect_bundle_paths(root, &path, out)?;
        } else if file_type.is_file() {
            out.push(path.strip_prefix(root)?.to_path_buf());
        } else {
            bail!(
                "repository contains an unsupported file: {}",
                path.display()
            );
        }
    }
    Ok(())
}

fn append_bundle_file(writer: &mut fs::File, path: &Path, bytes: &[u8]) -> Result<()> {
    let path = path
        .to_str()
        .ok_or_else(|| anyhow!("bundle path is not UTF-8"))?;
    let length = u32::try_from(path.len()).context("bundle path is too long")?;
    writer.write_all(&length.to_be_bytes())?;
    writer.write_all(path.as_bytes())?;
    writer.write_all(&(bytes.len() as u64).to_be_bytes())?;
    writer.write_all(bytes)?;
    Ok(())
}

#[derive(Debug, Deserialize)]
struct PackageMeta {
    id: String,
    version: String,
    #[serde(flatten)]
    _rest: serde_yaml::Value,
}

pub fn read_repository_index(repo_dir: &Path) -> Result<RepositoryManifest> {
    let manifest = parse_repository_index(repo_dir)?;
    validate_repository_index(&manifest)?;
    Ok(manifest)
}

fn parse_repository_index(repo_dir: &Path) -> Result<RepositoryManifest> {
    let path = repo_dir.join("repository.yaml");
    let bytes = fs::read(&path).with_context(|| format!("reading {}", path.display()))?;
    serde_yaml::from_slice(&bytes).with_context(|| format!("parsing {}", path.display()))
}

pub fn validate_repository_index(manifest: &RepositoryManifest) -> Result<()> {
    if manifest.schema != REPOSITORY_SCHEMA {
        bail!("unsupported repository manifest schema {}", manifest.schema);
    }
    validate_identifier("repository id", &manifest.id)?;
    if manifest.name.trim().is_empty() {
        bail!("repository name must be non-empty");
    }
    validate_repository_version(&manifest.version)?;
    if manifest.licenses_sha256.as_ref().is_some_and(|digest| {
        digest.len() != 64 || !digest.bytes().all(|byte| byte.is_ascii_hexdigit())
    }) {
        bail!("repository has an invalid licenses_sha256 digest");
    }
    if let Some(key) = &manifest.signing_key {
        validate_identifier("repository signing key id", &key.id)?;
        if key.algorithm != SIGNATURE_ALGORITHM {
            bail!(
                "unsupported repository signing key algorithm '{}'",
                key.algorithm
            );
        }
        let _: [u8; 32] = decode_array(&key.public_key, "repository public key")?;
    }
    semver::VersionReq::parse(&manifest.compatibility.halod)
        .context("parsing repository compatibility.halod")?;

    let mut ids = HashSet::new();
    let mut paths = HashSet::new();
    for package in &manifest.packages {
        validate_identifier("repository package id", &package.id)?;
        semver::Version::parse(&package.version)
            .with_context(|| format!("parsing package '{}' version", package.id))?;
        let normalized = normalized_relative_path(&package.path)?;
        if !ids.insert(package.id.as_str()) {
            bail!(
                "repository package id '{}' is declared more than once",
                package.id
            );
        }
        if !paths.insert(normalized.clone()) {
            bail!("repository package path '{normalized}' is declared more than once");
        }
        if package.sha256.len() != 64
            || !package.sha256.bytes().all(|byte| byte.is_ascii_hexdigit())
        {
            bail!(
                "repository package '{}' has an invalid sha256 digest",
                package.id
            );
        }
    }
    Ok(())
}

pub fn validate_compatibility(
    manifest: &RepositoryManifest,
    halod_version: &str,
    plugin_api: u32,
) -> Result<()> {
    if manifest.compatibility.plugin_api != plugin_api {
        bail!(
            "repository requires plugin API {}, but Halo supports {}",
            manifest.compatibility.plugin_api,
            plugin_api
        );
    }
    let requirement = semver::VersionReq::parse(&manifest.compatibility.halod)
        .context("parsing repository compatibility.halod")?;
    let current = semver::Version::parse(halod_version).context("parsing Halo package version")?;
    if !requirement.matches(&current) {
        bail!(
            "repository requires Halo '{}', current Halo is {}",
            manifest.compatibility.halod,
            current
        );
    }
    Ok(())
}

pub fn validate_repository_packages(repo_dir: &Path, manifest: &RepositoryManifest) -> Result<()> {
    validate_repository_index(manifest)?;
    for package in &manifest.packages {
        let dir = repo_dir.join(&package.path);
        if !dir.is_dir() {
            bail!(
                "repository package '{}' directory is missing: {}",
                package.id,
                dir.display()
            );
        }
        reject_symlinks(&dir)
            .with_context(|| format!("checking package '{}' for symlinks", package.id))?;
        let meta = read_package_meta(&dir)
            .with_context(|| format!("reading package '{}' manifest", package.id))?;
        if meta.id != package.id {
            return Err(PackageManifestMismatch {
                package: package.id.clone(),
                field: "id".into(),
                expected: package.id.clone(),
                actual: meta.id,
            }
            .into());
        }
        if meta.version != package.version {
            return Err(PackageManifestMismatch {
                package: package.id.clone(),
                field: "version".into(),
                expected: package.version.clone(),
                actual: meta.version,
            }
            .into());
        }
        let actual = package_hash(&dir)
            .with_context(|| format!("hashing repository package '{}'", package.id))?;
        if !actual.eq_ignore_ascii_case(&package.sha256) {
            return Err(PackageHashMismatch {
                package: package.id.clone(),
                expected: package.sha256.clone(),
                actual,
            }
            .into());
        }
    }
    Ok(())
}

/// Validate the complete repository without writing: structural metadata,
/// one-to-one top-level package discovery, identity/version, and package hash.
pub fn validate_repository(repo_dir: &Path, manifest: &RepositoryManifest) -> Result<()> {
    validate_repository_packages(repo_dir, manifest)?;
    let notice = repo_dir.join("licenses.txt");
    match (&manifest.licenses_sha256, notice.is_file()) {
        (Some(expected), true) => {
            let actual = file_sha256(&notice)?;
            if !actual.eq_ignore_ascii_case(expected) {
                bail!("repository licenses.txt hash mismatch: expected {expected}, got {actual}");
            }
        }
        (Some(_), false) => bail!("repository licenses.txt is missing"),
        (None, true) => bail!("repository index does not hash licenses.txt"),
        (None, false) => {}
    }
    let discovered = discover_packages(repo_dir)?;
    if discovered != manifest.packages {
        let indexed: Vec<_> = manifest
            .packages
            .iter()
            .map(|package| &package.id)
            .collect();
        let actual: Vec<_> = discovered.iter().map(|package| &package.id).collect();
        bail!("repository package index is stale (indexed: {indexed:?}, discovered: {actual:?})");
    }
    Ok(())
}

/// Discover top-level package directories and calculate their canonical hashes.
pub fn discover_packages(repo_dir: &Path) -> Result<Vec<RepositoryPackage>> {
    reject_symlinks(repo_dir)?;
    let mut packages = Vec::new();
    for entry in
        fs::read_dir(repo_dir).with_context(|| format!("reading {}", repo_dir.display()))?
    {
        let entry = entry?;
        let file_type = entry.file_type()?;
        if !file_type.is_dir() || entry.file_name() == ".git" {
            continue;
        }
        let dir = entry.path();
        if !dir.join("plugin.yaml").is_file() {
            continue;
        }
        let path = PathBuf::from(
            entry
                .file_name()
                .to_str()
                .ok_or_else(|| anyhow!("package directory name is not UTF-8"))?,
        );
        let meta = read_package_meta(&dir)?;
        let directory = normalized_relative_path(&path)?;
        if meta.id != directory {
            bail!(
                "package directory '{}' does not match plugin.yaml id '{}'",
                directory,
                meta.id
            );
        }
        validate_identifier("plugin id", &meta.id)?;
        semver::Version::parse(&meta.version)
            .with_context(|| format!("parsing package '{}' version", meta.id))?;
        packages.push(RepositoryPackage {
            id: meta.id,
            path,
            version: meta.version,
            sha256: package_hash(&dir)?,
        });
    }
    packages.sort_by(|left, right| left.id.as_bytes().cmp(right.id.as_bytes()));
    let mut ids = HashSet::new();
    for package in &packages {
        if !ids.insert(package.id.as_str()) {
            bail!("plugin id '{}' was discovered more than once", package.id);
        }
    }
    Ok(packages)
}

pub fn generated_manifest(
    repo_dir: &Path,
    current: &RepositoryManifest,
    version: Option<&str>,
) -> Result<RepositoryManifest> {
    let mut generated = current.clone();
    if let Some(version) = version {
        validate_repository_version(version).context("parsing requested repository version")?;
        generated.version = version.to_owned();
    }
    generated.packages = discover_packages(repo_dir)?;
    let notice = repo_dir.join("licenses.txt");
    generated.licenses_sha256 = notice.is_file().then(|| file_sha256(&notice)).transpose()?;
    validate_repository_index(&generated)?;
    Ok(generated)
}

pub fn canonical_index_bytes(manifest: &RepositoryManifest) -> Result<Vec<u8>> {
    validate_repository_index(manifest)?;
    let mut out = String::from(GENERATED_HEADER);
    out.push_str(&format!(
        "schema: {}\nid: {}\nname: {}\nversion: {}\n",
        manifest.schema,
        yaml_string(&manifest.id),
        yaml_string(&manifest.name),
        yaml_string(&manifest.version),
    ));
    if let Some(digest) = &manifest.licenses_sha256 {
        out.push_str(&format!(
            "licenses_sha256: {}\n\n",
            digest.to_ascii_lowercase()
        ));
    }
    if let Some(key) = &manifest.signing_key {
        out.push_str(&format!(
            "signing_key:\n  id: {}\n  algorithm: {}\n  public_key: {}\n\n",
            yaml_string(&key.id),
            yaml_string(&key.algorithm),
            yaml_string(&key.public_key),
        ));
    }
    out.push_str(&format!(
        "compatibility:\n  halod: {}\n  plugin_api: {}\n\npackages:\n",
        yaml_string(&manifest.compatibility.halod),
        manifest.compatibility.plugin_api
    ));
    let mut packages = manifest.packages.clone();
    packages.sort_by(|left, right| left.id.as_bytes().cmp(right.id.as_bytes()));
    for package in packages {
        out.push_str(&format!(
            "  - id: {}\n    path: {}\n    version: {}\n    sha256: {}\n",
            yaml_string(&package.id),
            yaml_string(&normalized_relative_path(&package.path)?),
            yaml_string(&package.version),
            package.sha256.to_ascii_lowercase()
        ));
    }
    Ok(out.into_bytes())
}

pub fn rewrite_index(repo_dir: &Path, version: Option<&str>, check: bool) -> Result<bool> {
    // Generation replaces the package list, so it can repair malformed or
    // stale digest fields in the current generated section.
    let current = parse_repository_index(repo_dir)?;
    let generated = generated_manifest(repo_dir, &current, version)?;
    let expected = canonical_index_bytes(&generated)?;
    let path = repo_dir.join("repository.yaml");
    let actual = fs::read(&path).with_context(|| format!("reading {}", path.display()))?;
    if actual == expected {
        return Ok(false);
    }
    if check {
        bail!("{} is not the canonical generated index", path.display());
    }
    atomic_write(&path, &expected)?;
    Ok(true)
}

/// Deterministic SHA-256 over sorted UTF-8 forward-slash relative paths,
/// file lengths, and bytes. Symlinks and non-UTF-8 paths are rejected.
pub fn package_hash(package_dir: &Path) -> Result<String> {
    reject_symlinks(package_dir)?;
    let mut files = Vec::new();
    collect_package_files(package_dir, package_dir, &mut files)?;
    files.sort_by(|left, right| left.0.as_bytes().cmp(right.0.as_bytes()));
    let mut hasher = Sha256::new();
    for (relative, path) in files {
        let bytes = fs::read(&path).with_context(|| format!("reading package file {relative}"))?;
        // Normalize so the digest is independent of checkout line endings (CRLF vs LF).
        let bytes = normalize_for_hash(bytes);
        hasher.update(relative.as_bytes());
        hasher.update([0]);
        hasher.update((bytes.len() as u64).to_le_bytes());
        hasher.update(&bytes);
    }
    Ok(hex_lower(hasher.finalize()))
}

/// Normalize CRLF pairs in text files so CRLF and LF hash identically.
/// Binary files (any NUL byte, git's heuristic) are left untouched so asset
/// bytes are never mangled.
fn normalize_for_hash(bytes: Vec<u8>) -> Vec<u8> {
    if bytes.contains(&0) {
        return bytes;
    }
    let mut normalized = Vec::with_capacity(bytes.len());
    let mut index = 0;
    while index < bytes.len() {
        if bytes[index] == b'\r' && bytes.get(index + 1) == Some(&b'\n') {
            normalized.push(b'\n');
            index += 2;
        } else {
            normalized.push(bytes[index]);
            index += 1;
        }
    }
    normalized
}

pub fn signature_bytes(key_id: &str, signature: &[u8; 64]) -> Vec<u8> {
    format!(
        "schema: {REPOSITORY_SCHEMA}\nalgorithm: {SIGNATURE_ALGORITHM}\nkey_id: {key_id}\nsignature: {}\n",
        B64.encode(signature)
    )
    .into_bytes()
}

pub fn verify_signature(
    payload: &[u8],
    signature_bytes: &[u8],
    trusted_keys: &[(&str, &str)],
) -> Result<()> {
    let signature: RepositorySignature =
        serde_yaml::from_slice(signature_bytes).context("parsing repository signature")?;
    if signature.schema != REPOSITORY_SCHEMA {
        bail!(
            "unsupported repository signature schema {}",
            signature.schema
        );
    }
    if signature.algorithm != SIGNATURE_ALGORITHM {
        bail!(
            "unsupported repository signature algorithm '{}'",
            signature.algorithm
        );
    }
    let key_b64 = trusted_keys
        .iter()
        .find_map(|(id, key)| (*id == signature.key_id).then_some(*key))
        .ok_or_else(|| anyhow!("unknown repository signing key '{}'", signature.key_id))?;
    let public: [u8; 32] = decode_array(key_b64, "repository public key")?;
    let raw_signature: [u8; 64] = decode_array(&signature.signature, "repository signature")?;
    let key = VerifyingKey::from_bytes(&public).context("constructing repository verifying key")?;
    key.verify(payload, &Signature::from_bytes(&raw_signature))
        .map_err(|_| RepositorySignatureMismatch.into())
}

pub fn verify_advertised_signature(
    payload: &[u8],
    signature_bytes: &[u8],
    key: &RepositorySigningKey,
) -> Result<()> {
    verify_signature(
        payload,
        signature_bytes,
        &[(key.id.as_str(), key.public_key.as_str())],
    )
}

pub fn signing_key_fingerprint(key: &RepositorySigningKey) -> Result<String> {
    let public: [u8; 32] = decode_array(&key.public_key, "repository public key")?;
    let digest = Sha256::digest(public);
    Ok(digest
        .chunks(2)
        .map(|chunk| format!("{:02X}{:02X}", chunk[0], chunk[1]))
        .collect::<Vec<_>>()
        .join(":"))
}

pub fn reject_symlinks(root: &Path) -> Result<()> {
    for entry in fs::read_dir(root).with_context(|| format!("reading {}", root.display()))? {
        let entry = entry?;
        let file_type = entry.file_type()?;
        if file_type.is_symlink() {
            bail!("repo contains a symlink: {}", entry.path().display());
        }
        if file_type.is_dir() && entry.file_name() != ".git" {
            reject_symlinks(&entry.path())?;
        }
    }
    Ok(())
}

fn read_package_meta(package_dir: &Path) -> Result<PackageMeta> {
    let path = package_dir.join("plugin.yaml");
    let bytes = fs::read(&path).with_context(|| format!("reading {}", path.display()))?;
    serde_yaml::from_slice(&bytes).with_context(|| format!("parsing {}", path.display()))
}

fn validate_identifier(label: &str, value: &str) -> Result<()> {
    if value.is_empty()
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-'))
    {
        bail!("{label} '{value}' must contain only ASCII letters, digits, '_' or '-'");
    }
    Ok(())
}

fn validate_repository_version(value: &str) -> Result<()> {
    if semver::Version::parse(value).is_ok() {
        return Ok(());
    }
    let calendar = value.split('.').collect::<Vec<_>>();
    if calendar.len() == 3
        && calendar
            .iter()
            .all(|part| !part.is_empty() && part.bytes().all(|byte| byte.is_ascii_digit()))
    {
        return Ok(());
    }
    bail!("repository version '{value}' is not semver or a numeric calendar version")
}

fn normalized_relative_path(path: &Path) -> Result<String> {
    if path.is_absolute() || path.as_os_str().is_empty() {
        bail!("invalid repository-relative path '{}'", path.display());
    }
    let mut parts = Vec::new();
    for component in path.components() {
        match component {
            Component::Normal(part) => parts.push(
                part.to_str()
                    .ok_or_else(|| anyhow!("path '{}' is not UTF-8", path.display()))?,
            ),
            _ => bail!("invalid repository-relative path '{}'", path.display()),
        }
    }
    Ok(parts.join("/"))
}

fn collect_package_files(
    root: &Path,
    current: &Path,
    out: &mut Vec<(String, PathBuf)>,
) -> Result<()> {
    for entry in fs::read_dir(current).with_context(|| format!("reading {}", current.display()))? {
        let entry = entry?;
        let file_type = entry.file_type()?;
        if file_type.is_symlink() {
            bail!("package contains a symlink: {}", entry.path().display());
        }
        if file_type.is_dir() {
            collect_package_files(root, &entry.path(), out)?;
        } else if file_type.is_file() {
            let relative = entry
                .path()
                .strip_prefix(root)
                .expect("walk remains under root")
                .to_owned();
            out.push((normalized_relative_path(&relative)?, entry.path()));
        } else {
            bail!(
                "package contains a non-regular file: {}",
                entry.path().display()
            );
        }
    }
    Ok(())
}

fn yaml_string(value: &str) -> String {
    // JSON strings are valid YAML scalars and give deterministic escaping.
    serde_yaml::to_string(value)
        .expect("serializing a string cannot fail")
        .trim()
        .trim_start_matches("---\n")
        .to_owned()
}

fn decode_array<const N: usize>(value: &str, label: &str) -> Result<[u8; N]> {
    B64.decode(value.trim())
        .with_context(|| format!("decoding {label}"))?
        .try_into()
        .map_err(|_| anyhow!("{label} is not {N} bytes"))
}

fn file_sha256(path: &Path) -> Result<String> {
    let bytes = fs::read(path).with_context(|| format!("reading {}", path.display()))?;
    Ok(hex_lower(Sha256::digest(bytes)))
}

fn hex_lower(bytes: impl AsRef<[u8]>) -> String {
    bytes
        .as_ref()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

fn atomic_write(path: &Path, bytes: &[u8]) -> Result<()> {
    let parent = path.parent().unwrap_or_else(|| Path::new("."));
    let mut temp = tempfile::NamedTempFile::new_in(parent)
        .with_context(|| format!("creating temporary file beside {}", path.display()))?;
    temp.write_all(bytes)?;
    temp.as_file().sync_all()?;
    temp.persist(path)
        .map_err(|error| error.error)
        .with_context(|| format!("replacing {}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn package(root: &Path, id: &str, version: &str) -> PathBuf {
        let dir = root.join(id);
        fs::create_dir_all(&dir).unwrap();
        fs::write(
            dir.join("plugin.yaml"),
            format!("id: {id}\nversion: {version}\n"),
        )
        .unwrap();
        fs::write(dir.join("main.lua"), "return {}\n").unwrap();
        dir
    }

    #[test]
    fn package_hash_changes_for_name_length_and_contents() {
        let root = tempfile::tempdir().unwrap();
        let dir = package(root.path(), "demo", "1.0.0");
        let original = package_hash(&dir).unwrap();
        fs::write(dir.join("main.lua"), "return {x=1}\n").unwrap();
        assert_ne!(original, package_hash(&dir).unwrap());
        fs::rename(dir.join("main.lua"), dir.join("renamed.lua")).unwrap();
        let renamed = package_hash(&dir).unwrap();
        assert_ne!(original, renamed);
        fs::write(dir.join("renamed.lua"), "return {x=10}\n").unwrap();
        assert_ne!(renamed, package_hash(&dir).unwrap());
    }

    #[test]
    fn package_hash_is_line_ending_independent() {
        let root = tempfile::tempdir().unwrap();
        let lf = root.path().join("lf");
        fs::create_dir_all(&lf).unwrap();
        fs::write(lf.join("plugin.yaml"), "id: demo\nversion: 1.0.0\n").unwrap();
        fs::write(lf.join("main.lua"), "return {\n  a = 1,\n}\n").unwrap();

        let crlf = root.path().join("crlf");
        fs::create_dir_all(&crlf).unwrap();
        fs::write(crlf.join("plugin.yaml"), "id: demo\r\nversion: 1.0.0\r\n").unwrap();
        fs::write(crlf.join("main.lua"), "return {\r\n  a = 1,\r\n}\r\n").unwrap();

        assert_eq!(package_hash(&lf).unwrap(), package_hash(&crlf).unwrap());
    }

    #[test]
    fn normalize_for_hash_is_noop_on_lf() {
        let lf = b"id: demo\nversion: 1.0.0\n".to_vec();
        assert_eq!(normalize_for_hash(lf.clone()), lf);
    }

    #[test]
    fn normalize_for_hash_preserves_lone_carriage_returns() {
        let text = b"before\rafter\n".to_vec();
        assert_eq!(normalize_for_hash(text.clone()), text);
    }

    #[test]
    fn normalize_for_hash_leaves_binary_untouched() {
        // A NUL byte marks the buffer binary, so a data CR must survive.
        let binary = vec![0x00, 0x0d, 0x0a, 0xff];
        assert_eq!(normalize_for_hash(binary.clone()), binary);
    }

    #[test]
    fn generated_index_is_sorted_lf_terminated_and_checkable() {
        let root = tempfile::tempdir().unwrap();
        package(root.path(), "zeta", "1.0.0");
        package(root.path(), "alpha", "2.0.0");
        let initial = RepositoryManifest {
            schema: 1,
            id: "test-repo".into(),
            name: "Test repository".into(),
            version: "1.0.0".into(),
            licenses_sha256: None,
            signing_key: None,
            compatibility: RepositoryCompatibility {
                halod: ">=0.2.0, <0.3.0".into(),
                plugin_api: 1,
            },
            packages: vec![],
        };
        fs::write(
            root.path().join("repository.yaml"),
            canonical_index_bytes(&initial).unwrap(),
        )
        .unwrap();
        assert!(rewrite_index(root.path(), Some("2026.7.1"), false).unwrap());
        assert!(!rewrite_index(root.path(), None, true).unwrap());
        let bytes = fs::read(root.path().join("repository.yaml")).unwrap();
        assert!(bytes.ends_with(b"\n"));
        assert!(!bytes.contains(&b'\r'));
        let text = String::from_utf8(bytes).unwrap();
        assert!(text.find("alpha").unwrap() < text.find("zeta").unwrap());

        let manifest = read_repository_index(root.path()).unwrap();
        let stale = text.replacen(&manifest.packages[0].sha256, "not-a-digest", 1);
        fs::write(root.path().join("repository.yaml"), stale).unwrap();
        assert!(rewrite_index(root.path(), None, false).unwrap());
        validate_repository(root.path(), &read_repository_index(root.path()).unwrap()).unwrap();
    }

    #[test]
    fn generated_index_hashes_the_plugin_license_notice() {
        let root = tempfile::tempdir().unwrap();
        package(root.path(), "demo", "1.0.0");
        let initial = RepositoryManifest {
            schema: 1,
            id: "test-repo".into(),
            name: "Test repository".into(),
            version: "1.0.0".into(),
            licenses_sha256: None,
            signing_key: None,
            compatibility: RepositoryCompatibility {
                halod: ">=0.2.0".into(),
                plugin_api: 1,
            },
            packages: vec![],
        };
        fs::write(
            root.path().join("repository.yaml"),
            canonical_index_bytes(&initial).unwrap(),
        )
        .unwrap();
        fs::write(root.path().join("licenses.txt"), "notice\n").unwrap();
        rewrite_index(root.path(), None, false).unwrap();
        let manifest = read_repository_index(root.path()).unwrap();
        assert!(manifest.licenses_sha256.is_some());
        validate_repository(root.path(), &manifest).unwrap();

        fs::write(root.path().join("licenses.txt"), "tampered\n").unwrap();
        assert!(validate_repository(root.path(), &manifest).is_err());
    }

    #[test]
    fn signature_verification_rejects_any_payload_change() {
        use ed25519_dalek::{Signer, SigningKey};
        let seed = [7_u8; 32];
        let key = SigningKey::from_bytes(&seed);
        let payload = b"schema: 1\n";
        let signature = key.sign(payload).to_bytes();
        let document = signature_bytes("test", &signature);
        let public = B64.encode(key.verifying_key().to_bytes());
        verify_signature(payload, &document, &[("test", &public)]).unwrap();
        let error = verify_signature(b"schema: 2\n", &document, &[("test", &public)]).unwrap_err();
        assert!(error.is::<RepositorySignatureMismatch>());
    }

    #[test]
    fn advertised_key_verifies_and_has_a_stable_fingerprint() {
        use ed25519_dalek::{Signer, SigningKey};
        let key = SigningKey::from_bytes(&[9; 32]);
        let advertised = RepositorySigningKey {
            id: "publisher".into(),
            algorithm: SIGNATURE_ALGORITHM.into(),
            public_key: B64.encode(key.verifying_key().to_bytes()),
        };
        let payload = b"repository index";
        let document = signature_bytes("publisher", &key.sign(payload).to_bytes());

        verify_advertised_signature(payload, &document, &advertised).unwrap();
        assert_eq!(signing_key_fingerprint(&advertised).unwrap().len(), 79);
        assert!(verify_advertised_signature(b"changed", &document, &advertised).is_err());
    }
}
