// SPDX-License-Identifier: GPL-3.0-or-later
pub mod capability;
pub mod chain;
pub mod debug;
pub mod keyboard_layout;
pub mod receiver;
pub mod registration;
pub mod rename;
pub mod settings;
pub mod visibility;
